ConvertFrom-StringData @'
ContentbtnAddRoom = Add room
ContentbtnAddRoomCancel = Cancel
ContentbtnAddRoomOk = OK
ContentbtnChangeOwner = Change owner
ContentbtnCreateRoomList = Create new room list
ContentbtnCreateRoomListCancel = Cancel
ContentbtnCreateRoomListOk = OK
ContentbtnRemoveRoom = Remove selected room
ContentdgRoomListsColListName = Name of room list
ContentdgRoomsInListColRoomName = Roomname
ContentlblAddRoomTitle = Enter name of room
ContentlblCreateRoomListTitle = Enter name and emailaddress of the new room list
ContentlblListRoomsTitle = Rooms that are members of the room list
ContentlblOwnerChangeInfo = Enter id, emailaddress or name in Exchange for new owner
ContentlblOwnerTitle = Owner:
ContentlblRoomListsList = Existing room lists
ErrLogAddRoom = Add room
ErrLogNewList = New room list
ErrLogNewOwner = New owner
ErrLogRemRoom = Remove room
ErrMsgNoRoom = No room found with name given
ErrMsgNoRoomsInList = <No rooms are connected to the room list>
ErrMsgNoUsr = Found no user matching the specified text
ErrMsgSame = The person is already listed as the owner
LogAddRoom = Added room
LogAddRoomUIRL = Room list:
LogAddRoomUIRoom = Room:
LogNewList = New room list
LogNewListUIRLName = Name
LogNewOwner = New owner
LogRemoveRoom = Remove room
LogRemoveRoomUIRL = Room list:
LogRemoveRoomUIRoom = Room:
StrGettingLists = Retrieves room lists
StrGettingsRoomsInList = Retrieves rooms linked to the room list
'@
