ConvertFrom-StringData @'
CodeMsExchIgnoreOrg = OU=Org5
ContentbtnActiveLogin = Save
ContentbtnGetDelegates = Get delegations
ContentbtnGetDevices = Get devices
ContentbtnGetDistsMember = Get memberships
ContentbtnGetDistsOwner = Get ownerships
ContentbtnGetIcon = Check if user has set a usericon
ContentbtnGetLogins = Get logins
ContentbtnGetSharedMember = Get memberships
ContentbtnGetSharedOwner = Get ownerships
ContentbtnID = Check O365-account status
ContentbtnRemoveIcon = Remove usericon
ContentgbAD = AD
ContentgbO365 = Azure / Exchange
ContentlblActiveLogin = Login active
ContentlblADActiveCheck = AD Active
ContentlblADCheck = Exists in AD
ContentlblADLockCheck = AD unlocked
ContentlblADMailCheck = Mailattribute
ContentlblADmsECheck = msExchMailboxGuid empty
ContentlblID = Enter user-Id
ContentlblLastO365Login = Last successfull Office 365-login:
ContentlblLastTeamsLogin = Last successfull Teams-login:
ContentlblOAccountCheck = O365-account
ContentlblOExchCheck = Synched to Exchange
ContentlblOLicCheck = E3-licens
ContentlblOLoginCheck = O365-login active
ContentlblOMigCheck = Member of O365-MigPilots
ContenttiDelegates = Delegations
ContenttiDevices = Registered devices
ContenttiDists = Distributiongroups
ContenttiDistsMember = Memberships
ContenttiDistsOwner = Ownerships
ContenttiIcon = Usericon
ContenttiLogins = Registered logins
ContenttiShared = Shared mailboxes
ContenttiSharedMember = Memberships
ContenttiSharedOwner = Ownerships
ErrNoCalendar = Could not find calendar
StrCalendar = Calendar
StrDgDelegatesTitleFolder = Folder
StrDgDelegatesTitlePerm = Permissions
StrDgDelegatesTitleUser = User
StrDgDistsMemberTitleName = Distributionsgroup
StrDgDistsMemberTitleSmtp = SMTP address
StrDgDistsOwnerTitleName = Distributiongroup
StrDgDistsOwnerTitleSmtp = SMTP address
StrDgSharedMemberTitleName = Shared mailbox
StrDgSharedMemberTitlePermission = SMTP address
StrDgSharedOwnerTitleName = Shared mailbox
StrDgSharedOwnerTitleSmtp = SMTP address
StrDoneGettingLogings = Logindates received
StrErrAD = Could not access AD-server. Import the ActiveDirectory-module.
StrErrAdDisabled = AD-account not active (Disabled)
StrErrAdLocked = AD-account is locked
StrErrADNF = ID could not be found in AD
StrErrMsExch = msExchMailboxGuid is not empty in AD
StrErrNoMail = Mailattribute not synched to AD
StrGettingLoggins = Getting logins, this will take a moment
StrGettingLogginsDelegates = (can not be done while logins are being retrieved)
StrIgnoreMsExch = Works in Org5, ignoring msExchMailboxGuid
StrInbox = Inbox
StrNoDistsMember = <Not member of any distributiongroup>
StrNoDistsOwner = <Not owner of any distributiongroup>
StrNoImage = No icon set on the accoun
StrNoLogin = No logins registered
StrNoMailDelegates = <No delegations are created>
StrNoSharedMember = <Not member of any shared mailbox>
StrNoSharedOwner = <Not owner of any shared mailbox>
StrO365IgnoreLicense = Works in Org5, does not get a licens.
StrO365LoginDisabled = Login to O365-account inactivated
StrO365NoAzAdConnection = Not connected to AzureAD
StrO365NoExchConnection = Not connected to Exchange
StrO365NoLicens = No E3-licens
StrO365NoMig = Is not member of O365-MigPilots
StrO365NoO365 = O365-account have not been created. Aborts remaning tests.
StrO365NotFound = O365-account have not been created
StrO365NotFoundExchange = Mailbox not created in Exchange
StrToday = Today
StrYesterday = Yesterday
'@
