ConvertFrom-StringData @'
CodeMsExchIgnoreOrg = OU=Org5
ContentbtnActiveLogin = Save
ContentbtnGetDelegates = Get delegations
ContentbtnGetDevices = Get devices
ContentbtnGetDistsMember = Get memberships
ContentbtnGetDistsOwner = Get ownerships
ContentbtnGetIcon = Check if user has set a usericon
ContentbtnGetLogins = Get logins
ContentbtnGetSharedMember = Get memberships
ContentbtnGetSharedOwner = Get ownerships
ContentbtnID = Check O365-account status
ContentbtnRemoveIcon = Remove usericon
ContentdgDelegatesColFolder = Folder
ContentdgDelegatesColPerm = Permissions
ContentdgDelegatesColUser = User
ContentdgDevicesColDisplayName = Display name
ContentdgDevicesColLastLogin = Approximate last login
ContentdgDistsMemberColName = Distribution list
ContentdgDistsMemberColSmtp = SMTP address
ContentdgDistsOwnerColName = Distribution list
ContentdgDistsOwnerColSmtp = SMTP address
ContentdgSharedMemberColName = Shared mailbox
ContentdgSharedMemberColPermission = SMTP address
ContentdgSharedOwnerColName = Shared mailbox
ContentdgSharedOwnerColSmtp = SMTP address
ContentgbAD = AD
ContentgbO365 = Azure / Exchange
ContentlblActiveLogin = Login active
ContentlblADActiveCheck = AD Active
ContentlblADCheck = Exists in AD
ContentlblADLockCheck = AD unlocked
ContentlblADMailCheck = Mailattribute
ContentlblADmsECheck = msExchMailboxGuid empty
ContentlblID = Enter user-Id
ContentlblLastO365Login = Last successfull Office 365-login:
ContentlblLastTeamsLogin = Last successfull Teams-login:
ContentlblOAccountCheck = O365-account
ContentlblOExchCheck = Synched to Exchange
ContentlblOLicCheck = E3-licens
ContentlblOLoginCheck = O365-login active
ContentlblOMigCheck = Member of O365-MigPilots
ContenttiDelegates = Delegations
ContenttiDevices = Registered devices
ContenttiDists = Distributiongroups
ContenttiDistsMember = Memberships
ContenttiDistsOwner = Ownerships
ContenttiIcon = Usericon
ContenttiLogins = Registered logins
ContenttiShared = Shared mailboxes
ContenttiSharedMember = Memberships
ContenttiSharedOwner = Ownerships
ErrLogConnFailAd = Could not search in AD
ErrLogGetPhoto = Retrieve icon image
ErrLogNoCal = No calendar could be found
ErrLogNotConn = Not connected to AzureAD
ErrLogNotFoundAd = Not found in AD
ErrLogNotFoundAzAd = Users not found in AzureAD
ErrLogNotInExc = Could not be found in Exchange
ErrLogSomeError = An error occurred
ErrMsgNoCalendar = Could not find calendar
ErrMsgO365NoAzAdConnection = Not connected to AzureAD
LogCalendarDelegatesTitle = Number of delegations for the calendar:
LogGetDelegates = Retrieving delegations
LogGetDistMemberships = Get membership in distribution lists
LogGetDistOwnerships = Get ownership for distribution lists
LogGetLastLogin = Get the latest login
LogGetOwnershipShared = Get ownership of shared mailboxes
LogGetSharedMemberships = Retrieve membership in shared mailboxes
LogGetUserAd = Retrieves user in AD
LogGetUserAzAd = Retrieves user in AzureAD
LogGetUserPhoto = Retrieves icon image
LogLastLoginO365 = Last logged in with Office365 account:
LogLastLoginTeams = Last logged in with Teams account:
LogMailDelegatesTitle = Number of delegations for mail:
LogNoDelegates = No delegations
LogNoDevices = No devices registered
LogNoDistsMember = Not a member of any distribution list
LogNoDistsOwner = Not the owner of any distribution list
LogNoSharedMember = Not a member of any shared mailbox
LogNoSharedOwner = Not the owner of any shared mailbox
LogRemovePhoto = Removed icon image
LogSetActive = Make the account active
StrCalendar = Calendar
StrErrAD = Unable to connect to AD server. Import the ActiveDirectory module.
StrErrAdDisabled = AD account not active (Disabled)
StrErrAdLocked = AD account is locked
StrErrADNF = ID not found in AD
StrErrGetUsr = User retrieval
StrErrMsExch = msExchMailboxGuid is not empty in AD
StrErrNoMail = The mail attribute is not synchronized to AD
StrGettingLoggins = Fetching logins, this may take a few minutes
StrGettingLogginsDelegates = (cannot be done while user logins are being retrieved) 
StrIgnoreMsExch = Employed within Org5, ignores msExchMailboxGuid
StrInbox = Inbox
StrNoDevices = <No devices registered>
StrNoDistsMember = <Not a member of any distribution list>
StrNoDistsOwner = <Not the owner of any distribution list>
StrNoImage = No image specified on the account
StrNoLogin = No logins registered
StrNoMailDelegates = <No delegations for mail>
StrNoSharedMember = <Not a member of any function mailbox>
StrNoSharedOwner = <Not the owner of any feature mailbox>
StrO365IgnoreLicense = Employed within Org5, no license is appointed.
StrO365LoginDisabled = Login with O365 account disabled
StrO365NoLicens = E3 license is missing
StrO365NoMig = Is not a member of O365-MigPilots
StrO365NotFound = O365 account has not been created. Cancels the rest of the tests.
StrO365NotFoundExchange = Mailbox not created in Exchange. Cancels the rest of the tests.
'@
