ConvertFrom-StringData @'
CodeRegExDomain = @test.com$
ContentbtnAddAdmin = Lägg till
ContentbtnAddMember = Lägg till
ContentbtnCheck = Hämta
ContentbtnCopyUsers = Kopiera
ContentbtnFetchAdmins = Läs in administratörer
ContentbtnFetchMembers = Läs in användare
ContentbtnRemoveMembersAzure = Ta bort medlem i Azure
ContentbtnRemoveMembersExchange = Ta bort medlem i Exchange
ContentbtnRemoveSelectedAdmins = Ta bort
ContentbtnReset = Återställ
ContentbtnSMAddress = Byt adress
ContentbtnSMName = Byt namn
ContentbtnSMOwner = Byt ägare
ContentbtnSyncToExchange = Starta synk
ContentcbAddMemberLoc = Azure, Exchange, Båda
ContentcbAddMemberPerm = Läsbehörighet, Full behörighet
ContentdgAdminsMailTitle = Mailadress
ContentdgAdminsNameTitle = Namn
ContentdgMembersMailTitle = Mailadress
ContentdgMembersNameTitle = Namn
ContentdgMembersPermissionTitle = Behörighetstyp
ContentgAddAdmin = Lägg till administratör
ContentgAddMembers = Lägg till medlem
ContentgMembersAzure = Medlemmar enligt Azure
ContentgMembersExchange = Medlemmar enligt Exchange
ContentgRemoveSelectedAdmins = Ta bort administörer
ContentlblAddAdmin = Ange ny administratör
ContentlblAddMember = Ange användar-id eller mailadress
ContentlblAddMemberLoc = Lägg till i:
ContentlblAddMemberPerm = Behörighetstyp:
ContentlblCopyUsers = Kopiera medlemmar och admins
ContentlblRemoveSelectedAdmins = Ta bort markerade administratörer
ContentlblSM = Ange namn eller mailadress för funktionsbrevlåda
ContentlblSMAddress = Primär SMTP-adress
ContentlblSMName = Namn
ContentlblSMOwner = Ägare
ContentlblSMOwnerAddr = Mailadress
ContentlblSMOwnerId = användar-id
ContentlblSyncToExchange = Starta manuell synkronisering till Exchange
ContenttiAdmins = Administratörer
ContenttiInfo = Info
ContenttiMembers = Medlemmar
StrAzureADGrpNameAdmSuffix = -Admin
StrAzureADGrpNameFullSuffix = -Full
StrAzureADGrpNamePrefix = MB-
StrAzureADGrpNameReadSuffix = -Read
StrConfirmNewOwner = byta ägare på funktionsbrevlådan
StrConfirmPrefix = Du är på väg att
StrConfirmRemoveMembers = användare är på väg att tas bort i
StrConfirmRename = byta namn på funktionsbrevlådan
StrConfirmSuffix = Är du säker på att du vill fortsätta?
StrImmutableIdPrefix = ID-
StrLogNewNameAddr = Nytt namn/adress
StrLogNewOwner = Ny ägare
StrNameOrAddrNotUpd = Vid byte av namn eller adress behöver detta även reflekteras i det andra värdet. Detta verkar inte ha gjorts. Ska de nuvarande värdena i textrutorna användas för den delade postlådan?
StrNoAdAccount = AD-konto finns inte
StrNoAdmins = <Inga administratörer angivna i Azure>
StrNoMailAccount = Hittar inget aktivt mailkonto med denna adress
StrNoUpdate = Funktionsbrevlådan uppdaterades inte
StrOwnerAttrPrefix = Owner:
StrPermFull = Full behörighet
StrPermRead = Läsbehörighet
StrPermSend = Behörighet att skicka som ombud
StrPermSendOnBehalf = Kan skicka som ombud
StrUsersCopied = Användare har kopierats till Clipboard
'@
