ConvertFrom-StringData @'
AdmList = gaisys6g1w, gaisysd833, gaisyscm7p
CompList = KARDS93260021, KARLS09941704, KARDS93549733, KARDS25863962, KARLS10522745, KARDS20157656, KARLS25810054
CompObjTitleBoot = Datum för omstart
CompObjTitleCompName = Datornamn
CompObjTitleFreeSpace = Ledigt diskutrymme
CompObjTitleFreeSpaceLow = Ledigt diskutrymme (Låg)
CompObjTitleIEVer = Internet Explorer version
CompObjTitleInst = Datum för installation
CompObjTitleModel = Model
CompObjTitleNetAd = Nätverksadaptrar
CompObjTitleOS = Operativsystem
CompObjTitleReinstAllowed = Ominstallation tillåten
CompObjTitleReinstNotAllowed = Ominstallation ej tillåten
CompObjTitleRole = PC-roll
CompObjTitleSinceBoot = Tid sedan omstart
CompObjTitleSN = Serienummer
ComputerFolder = Dator
ComputerNoReinstall = Ominstallera EJ denna PC
ComputerOffline = ... Misslyckades
ComputerOfflineMessage = Ingen kontakt med WinRM på dator, eller felaktigt datornamn. Skript beroende av WinRM kommer därför inte gå att starta.
ComputerOnline = Kontrollerar att datorn är nåbar
ComputerUnknownRole = Okänd-PC
ContentBtnAddScript = Lägg till namn på skript i meddelande
ContentbtnComputerConnect = Hämta info
ContentbtnComputerDisconnect = Avsluta
ContentbtnFeedbackSend = Skicka meddelande
ContentbtnListOutputFiles = Lista outputfiler
ContentbtnO365Connect = Starta
ContentbtnOpenOutputFile = Öppna fil
ContentBtnRun = Kör
ContentbtnSurveyCancel = Avbryt
ContentbtnSurveySave = Spara
ContentdgOutputFilesColDates = Senast uppdaterad
ContentdgOutputFilesColNames = Filnamn
ContentlblComputerNameTitle = Ange datornamn
ContentlblFeedbackType = Typ av meddelande
ContentLblInTest = Använd enbart om du tillfrågats
ContentlblRateTitle = Ange betyg på denna version av
ContentlblSurvey = Lämna gärna en kommentar
ContentlblO65 = Klicka på 'Starta' för öppna Valmeny för Office 365-skript
ContentrbReport = Felanmälan
ContentrbSuggestion = Förslag
ContentrbSurveyRate1 = 1
ContentrbSurveyRate2 = 2
ContentrbSurveyRate3 = 3
ContentrbSurveyRate4 = 4
ContentrbSurveyRate5 = 5
ContenttiBaseInfo = Basinformation
ContenttiOutputTool = Outputfiler
ContenttiReportTool = Felanmälan / Förslag
ContentWindow = SDValmeny
ContentWindowSurvey = Betygsätt och kommentera gärna skriptet
LogConnectingToComp = Ansluter till
LogOpenO365 = Startar SDGUI O365
O365Folder = O365
OrgList = kar|dan|sos
RoleList = Vård-PC|Administrativ-PC|Kiosk-PC
ScriptContentInDev = Dev
ScriptContentInTest = Test
StrAdmPrefix = gaisys
StrBaseInfoDays = dagar
StrBaseInfoHours = timmar
StrBaseInfoMinutes = minuter
StrBaseInfoNetAd = Nätverksadapter
StrBORole = Gai_Rol_Servicedesk_Backoffice
StrInfoCopied = har kopierats till Clipboard
StrMailAddress = servicedesk.backoffice.sfit@sll.se
StrMailSender = Från
StrNoOutputfiles = Inga outputfiler har skapats
StrOFListing = Listar outputfiler
StrOFOpenFile = Öppnar fil
StrOtherOrg = Annan organisation
StrSMTP = smtprelay.sll.se
StrSpecComp = AAA-dator
StrSplash = Läser in skript
'@
