ConvertFrom-StringData @'
AdmList = sysA, sysB, sysC
CompList = Comp1, Comp2
ComputerBaseInfo = Basinformation
ComputerFolder = Computer
ComputerNoReinstall = Ominstallera EJ denna PC
ComputerOffline = ... Misslyckades
ComputerOfflineMessage = Ingen kontakt med WinRM på dator, eller felaktigt datornamn. Skript beroende av WinRM kommer därför inte gå att starta.
ComputerOnline = Kontrollerar att datorn är nåbar
ComputerUnknownRole = Okänd-PC
ContentBtnAddScript = Lägg till namn på skript i meddelande
ContentBtnDisconnectComputer = Avsluta
ContentBtnGetComputerInfo = Hämta info
ContentBtnO365Connect = Starta
ContentBtnOutputList = Lista outputfiler
ContentBtnOutputListColumn = Filnamn
ContentBtnOutputOpenFile = Öppna fil
ContentBtnRun = Kör
ContentBtnSend = Skicka meddelande
ContentFeedbackHeader = Felanmälan / Förslag
ContentLblInTest = Använd enbart om du tillfrågats
ContentLblMessageType = Typ av meddelande
ContentO365Start = Klicka på 'Starta' för öppna Valmeny för Office 365-skript
ContentOutputToolHeader = Outputfiler
ContentRBtnErrorReport = Felanmälan
ContentRBtnSuggestion = Förslag
InputComputerName = Ange datornamn
O365Folder = O365
OrgList = Org1|Org2|Org3
RoleList = Role1|Role2|Role3
ScriptContentInDev = Dev
ScriptContentInTest = Test
StrAdmPrefix = sys
StrBORole = AD_BORole
StrDGRTriggerName = Dont Install
StrInfoCopied = har kopierats till Clipboard
StrMailAddress = servicedesk@test.com
StrMailSender = Från
StrNoOutputfiles = Inga outputfiler har skapats
StrOFListing = Listar outputfiler
StrOFOpenFile = Öppnar fil
StrOSParam = Operativsystem
StrOtherOrg = Annan organisation
StrScriptSuite = Skriptmeny
StrSMTP = smtp.test.com
StrSpecComp = Annan dator
StrSplash = Läser in skript
'@
