ConvertFrom-StringData @'
AdmList = sysA, sysB, sysC
CompList = Comp1, Comp2
ComputerBaseInfo = Basinformation
ComputerFolder = Computer
O365Folder = O365
ComputerNoReinstall = Ominstallera EJ denna PC
ComputerOffline = ... Misslyckades
ComputerOfflineMessage = Ingen kontakt med WinRM på dator, eller felaktigt datornamn. Skript beroende av WinRM kommer därför inte gå att starta.
ComputerOnline = Kontrollerar att datorn är nåbar
ComputerUnknownRole = Okänd-PC
ContentBtnAddScript = Lägg till namn på skript i meddelande
ContentBtnDisconnectComputer = Avsluta
ContentBtnGetComputerInfo = Hämta info
ContentBtnO365Connect = Starta
ContentO365Start = Klicka på 'Starta' för öppna Valmeny för Office 365-skript
ContentBtnRun = Kör
ContentBtnSend = Skicka meddelande
ContentFeedbackHeader = Felanmälan / Förslag
ContentLblInTest = Använd enbart om du tillfrågats
ContentLblMessageType = Typ av meddelande
ContentRBtnErrorReport = Felanmälan
ContentRBtnSuggestion = Förslag
InputComputerName = Ange datornamn
OrgList = Org1|Org2|Org3
RoleList = Role1|Role2|Role3
ScriptContentInDev = Dev
ScriptContentInTest = Test
StrAdmPrefix = sys
StrBORole = AD_BORole
StrInfoCopied = har kopierats till Clipboard
StrMailAddress = servicedesk@test.com
StrMailSender = Från
StrOSParam = Operativsystem
StrOtherOrg = Annan organisation
StrScriptSuite = Skriptmeny
StrSMTP = smtp.test.com
StrSpecComp = Annan dator
'@
