ConvertFrom-StringData @'
AdmList = sysA, sysB, sysC
CompList = Comp1, Comp2
ComputerBaseInfo = Basinformation
ComputerFolder = Dator
O365Folder = O365
ComputerNoReinstall = Ominstallera EJ denna PC
ComputerOffline = ... Misslyckades
ComputerOfflineMessage = Ingen kontakt med WinRM på dator, eller felaktigt datornamn. Skript beroende av WinRM kommer därför inte gå att starta.
ComputerOnline = Kontrollerar att datorn är nåbar
ComputerUnknownRole = Okänd-PC
ContentBtnAddScript = Lägg till namn på skript i meddelande
ContentBtnDisconnectComputer = Avsluta
ContentBtnGetComputerInfo = Hämta info
ContentBtnO365Connect = Anslut
ContentBtnRun = Kör
ContentBtnSend = Skicka meddelande
ContentFeedbackHeader = Felanmälan / Förslag
ContentLblInTest = Använd enbart om du tillfrågats
ContentLblMessageType = Typ av meddelande
ContentLblO365Connected = Anluten till
ContentO365Start = Klicka på 'Anslut' för att ansluta till O365-tjänster
ContentRBtnErrorReport = Felanmälan
ContentRBtnSuggestion = Förslag
InputComputerName = Ange datornamn
OrgList = Org1|Org2|Org3
RoleList = Role1|Role2|Role3
ScriptContentInDev = under utveckling
ScriptContentInTest = under testning
StrAdmPrefix = sys
StrInfoCopied = har kopierats till Clipboard
StrMailAddress = servicedesk@test.com
StrMailSender = Från
StrOSParam = Operativsystem
StrOtherOrg = Annan organisation
StrScriptSuite = Skriptmeny
StrSMTP = smtp.test.com
StrSpecComp = Annan dator
'@
