ConvertFrom-StringData @'
CodeMsExchIgnoreOrg = OU=Org5
ContentbtnActiveLogin = Spara
ContentbtnGetDelegates = Hämta delegeringar
ContentbtnGetDevices = Hämta enheter
ContentbtnGetDistsMember = Hämta medlemskap
ContentbtnGetDistsOwner = Hämta ägarskap
ContentbtnGetIcon = Kontrollera om användaren har individuell ikon
ContentbtnGetLogins = Hämta inloggningar
ContentbtnGetSharedMember = Hämta medlemskap
ContentbtnGetSharedOwner = Hämta ägarskap
ContentbtnID = Kontrollera O365 status
ContentbtnRemoveIcon = Ta bort ikon
ContentdgDelegatesColFolder = Mapp
ContentdgDelegatesColPerm = Behörigheter
ContentdgDelegatesColUser = Användare
ContentdgDevicesColDisplayName = Visningsnamn
ContentdgDevicesColLastLogin = Ungefärlig senast inloggning
ContentdgDistsMemberColName = Distributionslista
ContentdgDistsMemberColSmtp = SMTP adress
ContentdgDistsOwnerColName = Distributionslista
ContentdgDistsOwnerColSmtp = SMTP adress
ContentdgSharedMemberColName = Funktionsbrevlåda
ContentdgSharedMemberColPermission = SMTP adress
ContentdgSharedOwnerColName = Funktionsbrevlåda
ContentdgSharedOwnerColSmtp = SMTP adress
ContentgbAD = AD
ContentgbO365 = Azure / Exchange
ContentlblActiveLogin = Inloggning aktiverad
ContentlblADActiveCheck = AD Aktiv
ContentlblADCheck = Finns i AD
ContentlblADLockCheck = AD Olåst
ContentlblADMailCheck = Mailattribut angivet
ContentlblADmsECheck = msExchMailboxGuid tom
ContentlblID = Ange användar-id
ContentlblLastO365Login = Senast lyckade Office 365-inloggning:
ContentlblLastTeamsLogin = Senast lyckade Teams-inloggning:
ContentlblOAccountCheck = O365-konto
ContentlblOExchCheck = Synkat till Exchange
ContentlblOLicCheck = E3-licens
ContentlblOLoginCheck = O365 inloggning aktiv
ContentlblOMigCheck = Medlem i O365-MigPilots
ContenttiDelegates = Delegeringar
ContenttiDevices = Registrerade enheter
ContenttiDists = Distributionslistor
ContenttiDistsMember = Medlemskap
ContenttiDistsOwner = Ägarskap
ContenttiIcon = Användarikon
ContenttiLogins = Registrerade inloggningar
ContenttiShared = Funktionsbrevlådor
ContenttiSharedMember = Medlemskap
ContenttiSharedOwner = Ägarskap
ErrLogConnFailAd = Kunde inte söka i AD
ErrLogGetPhoto = Hämta ikonbild
ErrLogNoCal = Ingen kalender kunde hittas
ErrLogNotConn = Inte ansluten till AzureAD
ErrLogNotFoundAd = Hittades inte i AD
ErrLogNotFoundAzAd = Användare hittades inte i AzureAD
ErrLogNotInExc = Kunde inte hittas i Exchange
ErrLogSomeError = Fel uppstod
ErrMsgNoCalendar = Kunde inte hitta kalendern
ErrMsgO365NoAzAdConnection = Inte ansluten till AzureAD
LogCalendarDelegatesTitle = Antal delegeringar för kalendern:
LogGetDelegates = Hämtar delegeringar
LogGetDistMemberships = Hämta medlemskap i distributionslistor
LogGetDistOwnerships = Hämta ägarskap för distributionslistor
LogGetLastLogin = Hämta senaste inloggning
LogGetOwnershipShared = Hämta ägarskap för funktionsbrevlådor
LogGetSharedMemberships = Hämta medlemskap i funktionsbrevlådor
LogGetUserAd = Hämtar användare i AD
LogGetUserAzAd = Hämtar användare i AzureAD
LogGetUserPhoto = Hämta ikonbild
LogLastLoginO365 = Senast inloggad med Office365-konto:
LogLastLoginTeams = Senast inloggad med Teams-konto:
LogMailDelegatesTitle = Antal delegeringar för mail:
LogNoDelegates = Inga delegeringar
LogNoDevices = Inga enheter registrerade
LogNoDistsMember = Inte medlem i någon distributionslista
LogNoDistsOwner = Inte ägare av någon distributionslista
LogNoSharedMember = Inte medlem i någon funktionsbrevlåda
LogNoSharedOwner = Inte ägare av någon funktionsbrevlåda
LogRemovePhoto = Tog bort ikonbild
LogSetActive = Gör kontot aktivt
StrCalendar = Kalender
StrErrAD = Kan inte ansluta till AD-server. Läs in ActiveDirectory modulen.
StrErrAdDisabled = AD-konto ej aktivt (Disabled)
StrErrAdLocked = AD-konto är låst
StrErrADNF = ID hittas inte i AD
StrErrGetUsr = Hämtning av användare
StrErrMsExch = msExchMailboxGuid är inte tomt i AD
StrErrNoMail = Mailattributet ej synkroniserat till AD
StrGettingLoggins = Hämtar inloggningar, detta kan ta någon minut
StrGettingLogginsDelegates = (kan ej göras samtidigt som inloggningar hämtas)
StrIgnoreMsExch = Anställd inom Org5, ignorerar msExchMailboxGuid
StrInbox = Inkorg
StrNoDevices = <Inga enheter registrerade>
StrNoDistsMember = <Inte medlem i någon distributionslista>
StrNoDistsOwner = <Inte ägare för någon distributionslista>
StrNoImage = Ingen bild angiven på kontot
StrNoLogin = Inga inloggningar registrerade
StrNoMailDelegates = <Inga delegeringar för mail>
StrNoSharedMember = <Inte medlem i någon funktionsbrevlåda>
StrNoSharedOwner = <Inte ägare för någon funktionsbrevlåda>
StrO365IgnoreLicense = Anställd inom Org5, tilldelas ingen licens.
StrO365LoginDisabled = Inloggning med O365-konto inaktiverat
StrO365NoLicens = E3-licens saknas
StrO365NoMig = Är inte medlem i O365-MigPilots
StrO365NotFound = O365-konto har inte skapats. Avbryter resten av testerna.
StrO365NotFoundExchange = Mailbox inte skapad i Exchange. Avbryter resten av testerna.
'@
