ConvertFrom-StringData @'
CodeGetGGroupRead1 = "$( $Customer )_$( $entry )_file_UserR"
CodeGetGGroupRead2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetGGroupWrite1 = "$( $Customer )_$( $entry )_file_UserC"
CodeGetGGroupWrite2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetRGroupRead1 = "$( $Customer )_$( $entry )_file_UserR"
CodeGetRGroupRead2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetRGroupRead3 = "$( $FolderName )$( $Customer )_$( $entry )_file_02_UserR"
CodeGetRGroupRead4 = "$( $FolderName )$( $Customer )_$( $entry )_file_03_UserR"
CodeGetRGroupWrite1 = "$( $Customer )_$( $entry )_file_UserC"
CodeGetRGroupWrite2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserC"
CodeGetRGroupWrite3 = "$( $FolderName )$( $Customer )_$( $entry )_file_02_UserC"
CodeGetRGroupWrite4 = "$( $Customer )_$( $entry )_file_03_UserC"
CodeGetSGroupRead1 = "$( $Customer )_$( $entry )_file_UserR"
CodeGetSGroupRead2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetSGroupWrite1 = "$( $Customer )_$( $entry )_file_UserC"
CodeGetSGroupWrite2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserC"
ContentbtnPerform = Utför ändringar
ContentbtnUndo = Avbryt
ContentFoldersChosen = Valda mappar
ContentlblDisk = Välj disk
ContentlblFolderList = Välj mapp genom dubbeklick
ContentlblFolderSearch = Sök (hela eller del av namnet)
ContentlblLog = Utfört arbete
ContentlblUsersForReadPermission = Läs behörighet
ContentlblUsersForRemovePermission = Ta bort behörighet
ContentlblUsersForWritePermission = Skriv / läs behörighet
ErrNotFoundUser = Hittade ingen användare med id
ErrNotFoundGrpForGRead = Hittade ingen AD-grupp för Read på G för mapp
ErrNotFoundGrpForGWrite = Hittade ingen AD-grupp för Write på G för mapp
ErrNotFoundGrpForRRead = Hittade ingen AD-grupp för Read på R för mapp
ErrNotFoundGrpForRWrite = Hittade ingen AD-grupp för Write på R för mapp
ErrNotFoundGrpForSRead = Hittade ingen AD-grupp för Read på S för mapp
ErrNotFoundGrpForSWrite = Hittade ingen AD-grupp för Write på S för mapp
LogAddedToGroup = La till användare i grupp
LogInputRead = För läsbehörighet
LogInputWrite = För skrivbehörighet
LogInputRemove = För borttag
LogInputGroups = Grupper
LogMessageGroups = Grupper
LogMessageRead = Läsbehörighet
LogMessageWrite = Skrivbehörighet
LogMessageRemove = Tagit bort behörighet
LogMessageUsersNotFound = Dessa användare hittades inte
LogMessageGroupsNotFound = Dessa grupper hittades inte
LogRemovedFromGroup = Tog bort användare från grupp
StrConfirm1 = Vill du för
StrConfirm2 = mappar utföra
StrConfirm3 = ändringar
StrConfirmDups = Det finns värden listat för fler än en behörighetsgrupp. Rätta till och kör igen.
StrConfirmDupsTitle = Dubbletter
StrConfirmErr = Vissa värden har inga AD-objekt.
StrConfirmTitle = Fortsätta?
StrEGroupDn = sllEkDn
StrEGroupIdName = hsaIdentity
StrEGroupOrg = SE2321000016
StrFinIntro = Följande mappar har fått behörighetsförändringar enligt nedan
StrFinished1 = ändringar utförda
StrFinished2 = Ett lösningsmeddelande har kopierats till clipboard
StrFinNoAccounts = Hittade inget konto för följande
StrFinNoAdGroups = Hittade inga behörighetsgrupper för följande mappar
StrFinPermRead = Skapat läsbehörighet för
StrFinPermRem = Tagit bort behörighet för
StrFinPermWrite = Skapat skriv-/läsbehörighet för
StrGetFolders = Hämtar mappar...
StrNoPerm = Du saknar nödvändiga rättigheter för att köra detta skript.
StrNoPermTitle = Behörighetsproblem
StrOpErrLogFile = \\Errorlogs\\
StrOpGroup = Gai_Rol_Katalog_Drift
StrOpLogPath = \\\\gainaslit01.gaia.sll.se\\fs_lit_grp$\\KatValmeny2019\\Results\\FolderTool
StrPermRead = Läsbehörighet
StrPermReadWrite = Skriv-/läsbehörighet
StrPermRemove = Ta bort behörighet
StrPreping = Förbereder...
StrSDGroup = Gai_Rol_Servicedesk
StrSign = Med vänliga hälsningar
StrSignOp = SF IT, Region Stockholm
StrSignSD = SF IT Servicedesk, Region Stockholm
StrStart = Tillämpar gruppbehörigheter
StrStartPrep = Hämtar användare för
StrTitle = Ta bort/lägg till mappbehörigheter
StrTitleProgressGroups = Hämtar AD-grupper
'@
