ConvertFrom-StringData @'
CodeDescReplace = (\. Denna grupp skall populeras med användarkonton)|(\. Denna grupp skall EJ populeras med användarkonton)|(Ger Modify på )|(Ger ReadAndExecute på )|( för externa användare)
CodeMatchAppGrp =     \\\\\\dfs\\\\app\\$\\\\
CodeMatchDescGGroup = \\\\\\dfs\\\\gem\\$\\\\
CodeMatchDescSGroup = \\\\\\dfs\\\\sgem\\$\\\\
CodeMatchFullPermGrp = \.*_F\$
CodeMatchReadPermGrp = \.*_R\$
CodeMatchSpecialArea = dom01\|dom02
CodeMatchWritePermGrp = \.*_C\$
ErrLogUserNotFound = finns inte i AD
LogGroupCount = grupper
LogUserCount = användare
QDisplayOptions = Ska informationen visas i detta fönster (1), eller ska den visas i Notepad (2)?
QSearchGranularity = Ska behörighetssökningen vara grundlig? Tar då längre tid ( Y / N )
StrEnd = Nu är hela skriptet färdigt och alla användare har fått en egen lista utskriven i Output-mappen. Du kan använda Output-tabben i Skriptmeny för att öppna filerna.
StrFolderPermissionsG = Mappbehörigheter till G
StrFolderPermissionsR = Mappbehörigheter till R
StrFolderPermissionsS = Mappbehörigheter till S
StrNotepad = Notepad öppnas, ange användare
StrNotepadTitle = Ange id för användare, ett per rad
StrOpeningFile = Öppnar filen för
StrOpTitle = Hämtar alla grupper för
StrOutTitle = är tilldelad som medlem i följande behörighetsgrupper
StrPLvlChange = Skrivbehörighet
StrPLvlFull = Full behörighet
StrPLvlRead = Läsbehörighet
StrTitle = Detta skript hämtar och sorterar alla behörighetsgrupper för en eller flera användare. Alla filrättigheter exporteras sedan till en TXT-fil per användare
StrTitleAppGroups = Applikationsmappar
StrTitleOtherFiles = Andra filbehörigheter
StrTitleOtherGroups = Andra gruppbehörigheter
StrTitleSubGroups = grupper
StrUnknownIdsCount = användarkonton hittades inte
StrUnknownPerm = Okänd behörighet
StrUserNotFound = Hittade inte användare med id:
'@
