ConvertFrom-StringData @'
CodeAdNameReadSuffix = _User_R
CodeAdNameWriteSuffix = _User_C
CodeOrg1GrpPrefix = Org1_File_grp_
CodeOrg2GrpPrefix = Org2_File_grp_
CodeOrg3GrpPrefix = Org3_File_grp_
ErrLogAdUserDisabled = Ny ägare inaktiv i AD
ErrLogAdUserNotFound = Kontroll av ny ägare
ErrLogPath = existerar inte
ErrMsgAdUserDisabled = är inaktiv i AD
ErrMsgNoAdUser = Id för ny ägare finns ej i AD
ErrMsgPath = Hittar ingen mapp med sökväg
LogAbortingInit = Avbröts vid start
LogAbortingOwner = Avbröts vid ny ägare
LogAdUserDisabled = Önskad ny ägare inaktiv i AD
LogAdUserNotFound = Id för ny ägare finns ej i AD
StrAborting = Avslutar skriptet
StrCurrOwnerInfo = Nuvarande ägare för mappen:
StrCustomerInput = Angiven organisation:
StrDiffOwnerInfo1 = har olika mappägare. En för Read- och en för Change-gruppen.
StrDiffOwnerInfo2 = Om du anger en ny ägare kommer den läggas på båda grupperna.
StrDiffOwnerReadTitle = Ägare för Read-gruppen
StrDiffOwnerWriteTitle = Ägare för Change-gruppen
StrInfoEnd = Om du vill byta ägare så ange det nedan. Annars, avbryt scriptet.
StrInvalidOrgInput = Fel kund! Ange korrekt värde för att fortsätta.
StrNewOwnerInfo = Ägare är nu satt till
StrNoReadOwner = Ägare för Read-gruppen saknas
StrNoWriteOwner = Ägare för Change-gruppen saknas
StrOrg1 = Org1
StrOrg2 = Org2
StrOrg3 = Org3
StrOwnerInput = Angiven ny ägare:
StrQName = Ange mappnamn
StrQNewOwner = Ange id för ny ägare, Q för att avbryta
StrQOrg = Ange kund (Org1/Org2/Org3), Q för att avsluta
'@
