ConvertFrom-StringData @'
ContentbtnActivate = Activate account
ContentbtnCancel = Cancel
ContentbtnExtend = Extend password validity period
ContentbtnUnlock = Unlock account
ContentlblID = Enter ID or account name
ContentWTitle = AD account control
ErrActivate = Error - Activation
ErrExtendPassword = Error - Extension of password validity
ErrLActivate = Could not activate account. Error message
ErrLExtendPassword = Could not extend password validity. Error message
ErrLogActivate = Activation of account
ErrLogExtendPassword = Extension of password validity. Error message
ErrLogUnlock = Unlocking account. Error message
ErrLUnlock = Could not unlock account. Error message
ErrMessageActivate = Some accounts can only be activated by Operations
ErrMessageExtendPassword = Some accounts can only be managed by Operations.
ErrMessageUnlock = Some accounts can only be unlocked by Operations
ErrUnlock = Error - Unlocking account
WActivate = Activated
WActiveUser = Account Status: The account is enabled and unlocked
WBlockedUser = Account status: The account is deactivated and SHOULD NOT BE ACTIVATED! Escalate the case to the Operation
WDescText = THIS USER SHOULD NOT BE ACTIVATED, CONTACT OPERATIONS FOR MORE INFO
WDisabledUser = Account status: The account is disabled: To activate the account, see Knowledge 'AD account has been Disabled'
WExpiredPassword = Password status: The password is over 200 days old and has expired. Extend the validity of the existing password with the 'Extend password' button below. The password expired
WFutureExpiry = Password status: The password expires
WLActivate = Account activated.
WLActiveUser = Active
WLBlockedUser = inactive > Operations
WLDisabledUser = inactive
WLExpiredPassword = password validity passed
WLFutureExpiry = active password
WLLockedUser = locked
WLManualExpiry = manual validity period > Operations
WLManualExpiryEnded = manual validity period passed > Operation
WLNeverEndingPassword = infinite password
WLockedUser = The account is locked due to too many incorrect login attempts, see Knowledge 'AD account is locked'
WLPasswordChange = password change at the next login
WLPasswordExtended = The validity period of the password has been extended.
WLUnlocked = The account has been unlocked.
WManualExpiry = Validity period: The account has a manual validity date (Account expires). The account is managed by Operations. The validity period expires
WManualExpiryEnded = Validity period: The account has a manual expiration date that has passed (the Account expires date has passed). Escalate the case to the Operation. The account expired
WNeverEndingPassword = Password status: The password never expires
WNotFoundInAd = not found in AD
WPasswordChange = Password status: A password change is queued ('User must change password at next logon' is checked). Ask the user to log in with the new password they should have recently received. Alternatively, set a new password for the user (see Knowledge for password change in AD according to the user's organization affiliation).
WPasswordExtended = Validity of password extended
WReadUser = Loaded user
WUnlocked = Unlocked
'@
