ConvertFrom-StringData @'
ContentbtnCreateQuestion = Copy the question about help, to Operations
ContentbtnOpenSummary = Open file
ContentBtnReset = Reset
ContentBtnSearch = Search
ContentFilterTitle = Files that match filters
ContentlblCaseNrTitle = Enter case number
ContentlblFileCountTitle = Total number of files:
ContentLblFiles = Lists all files in folders the user has access to.
ContentLblFiles2W = Lists all files updated in the last two weeks, in folders the user has access to.
ContentLblFilterTitle = Some files match filters
ContentlblIDTitle = Enter user ID
ContentlblMDG = Files with multiple points in the file name (potentially multiple file extensions)
ContentlblMDH = Files in the H folder with multiple points in the file name (potentially multiple file extensions)
ContentlblO = Folders you do not have access to, escalate case to Driften
ContentlblSummaryTitle = Summary written to:
ContentlblUserTitle = User:
ContentlblValuesTitle = Both values must be specified:
ContentlvColumnCreated = Created
ContentlvColumnName = Name
ContentlvColumnUpdated = Updated
ContentrbAll = Search all files
ContentrbAllToolTip = Retrieves all files, regardless of date. When searching for all files, this will be done sequentially and will take longer.
ContentrbLatest = Search only for the last two weeks
ContentrbLatestToolTip = Retrieves the files that have been modified within the last two weeks
ContentrbPrevDate = Search from given date:
ContentrbPrevDateToolTip = Retrieves files modified after the specified date
ContenttiFilesHeader = All files
ContenttiMDGHeader = Multiple file extensions on G:
ContenttiMDHHeader = Multiple file extensions on H:
ContenttiOHeader = Folders you do not have permission for
ErrInvalidCaseNr = A valid case number must be entered.
ErrInvalidID = No account was found with the specified ID.
MQCopied = Text has been copied to the clipboard
MQLCopied = Copied
StrOutput1 = Search for potential viruses
StrOutput2 = User
StrOutput3 = Case number
StrOutput4 = Total number of files:
StrOutputTimeline1 = Searched: Files updated in the last two weeks
StrOutputTimeline2 = Searched: Filters updated by date
StrOutputTimeline3 = Searched: All available files
StrOutputTitle1 = Searched folders
StrOutputTitle2 = All found files
StrOutputTitle3 = Multiple file extensions
StrOutputTitle4 = Multiple file extensions
StrOutputTitle5 = Did not have permission for
WFilteringFolders = Filters found folders
WGettingFiles = Starts fetching files
WGettingFilesTitle = Loading files in
WGettingFolders = Retrieving folders
WLStart = Start
WQ1 = has reported possible virus in the case
WQ2 = Folders under H:\\ and G:\\ have been examined, but there is no permission for the folders below.
WQ3 = Can you help look at these?
WWaitGettingFiles = Awaiting file collection
'@
