ConvertFrom-StringData @'
ContentbtnCreateQuestion = Copy help request to Operation
ContentbtnOpenFolder = Open folder
ContentbtnOpenFolderTT = Open the folder where the file is located
ContentbtnOpenSummary = Open file
ContentbtnReset = Cancel
ContentbtnReset2 = Reset
ContentbtnSearch = Start search
ContentbtnSearchExt = Search for file extension
ContentbtnSearchExtTT = Search for file extension on Google
ContentbtnSearchFileName = Search filename
ContentbtnSearchFileNameTT = Search for the filename on Google
ContentcbExpandGroups = Expand all file extension-groups
ContentgbDatePicker = Date of oldest file change
ContentgbInfo = Summary
ContentgbSearch = Search settings
ContentgbSettings = Settings
ContentlblCaseNrTitle = Please enter the case number
ContentlblFileCountTitle = Total number of files:
ContentLblFiles = Lists all files in folders the user has access to.
ContentLblFiles2W = Lists all files updated in the last two weeks, in folders the user has access to.
ContentlblFilterMatch = Files that match the specified filter
ContentlblFolderCountTitle = Number of folders scanned:
ContentlblIDTitle = Enter user ID
ContentlblMDG = Files with multiple periods in the filename (potentially multiple file extensions)
ContentlblMDH = Files in the H folder with multiple periods in the file name (potentially multiple file extensions)
ContentlblO = Folders you do not have access to, add case to Operations
ContentlblSettings = Settings
ContentlblSummaryTitle = Summary written to:
ContentlblUserTitle = User:
ContentlblValuesTitle = Both values ​​must be specified:
ContentlvColumnCreated = Created
ContentlvColumnName = Name
ContentlvColumnUpdated = Updated
ContentrbAll = Search all files
ContentrbAllToolTip = Retrieves all files, regardless of date. When searching for all files, this can take longer to finish.
ContentrbLatest = Last two weeks
ContentrbLatestToolTip = Retrieves the files that have been modified within the last two weeks
ContentrbPrevDateToolTip = Retrieves files modified after the specified date
ContenttbPrevDateText = From given date:
ContenttiFilesHeader = All files
ContenttiFilterMatchHeader = Matches filters
ContenttiMDGHeader = Multiple file extensions on G:
ContenttiMDHHeader = Multiple file extensions on H:
ContenttiOHeader = Folders you do not have access to
ErrInvalidCaseNr = A valid case number must be specified.
ErrInvalidID = No account was found with the specified id.
StrDescSplit = on
StrFileSearchFinished = Finished searching for files
StrFilterTitle = Files that match filters
StrLogQuestionCopied = Copied
StrLogScriptStart = Start
StrNoExtension = <No fileextension>
StrOPFilteringFolders = Filters found folders
StrOPGettingFiles = Starts retrieving files
StrOPGettingFolders = Collects folders
StrOPWaitGettingFiles = Pending file retrieval
StrOutput1 = Scanning for potential viruses
StrOutput2 = User
StrOutput3 = Case number
StrOutput4 = Total number of files:
StrOutputTimeline1 = Searched: Files updated in the last two weeks
StrOutputTimeline2 = Searched: Files updated by date
StrOutputTimeline3 = Searched: All available files
StrOutputTitleAllFiles = All files found
StrOutputTitleFilterMatch = These files matched filters
StrOutputTitleFilterMatch2 = Specified filter:
StrOutputTitleFolders = Searched folders
StrOutputTitleMultiDotH = Multiple file extensions H:
StrOutputTitleMultiDotG = Multiple file extensions G:
StrOutputTitleFoldersOtherPerm = No access for the following folders
StrQuestion1 = has reported potential virus in the case
StrQuestion2 = Folders under H: \\ and G: \\ have been examined, but access is limited for the folders below.
StrQuestion3 = Can you help look at these?
StrQuestionCopied = Text has been copied to the clipboard
'@