ConvertFrom-StringData @'
ContentbtnCheckForUpdates = Sök efter uppdateringar
ContentbtnDoRollback = Rulla tillbaka filversion
ContentbtnListRollbacks = Lista rollbacks
ContentbtnOpenErrorLog = Öppna fellogg
ContentbtnOpenOutputFile = Öppna fil
ContentbtnOpenRollbackFile = Öppna fil
ContentbtnReadErrorLogs = Läs in felloggar
ContentbtnReadLogs = Läs in loggar
ContentbtnUpdateScripts = Uppdatera markerade filer
ContentdgErrorLogsColLogDate = Loggningstid
ContentdgLogsColLogDate = Loggningstid
ContentdgLogsColOperator = Handläggare
ContentdgLogsColSuccess = Framgång
ContentdgRollbacksColDate = Fildatum
ContentdgRollbacksColUpdatedBy = Uppdaterad av
ContentdgUpdatesColDevUpd = Uppdaterad i development
ContentdgUpdatesColName = Namn
ContentdgUpdatesColPath = Sökväg
ContentdgUpdatesColProdState = Utvecklingsfas
ContentdgUpdatesColProdUpd = Uppdaterad i produktion
ContentgbErrorInfo = Information om felmeddelandet
ContentlblErrorMessage = Felmeddelande
ContentlblLogErrorLogTitle = Fellog
ContentlblLogOutputFileTitle = Fil för utdata
ContentlblLogTextTitle = Logtext
ContentlblLogUserInputTitle = Angiven input
ContentlblOperator = Handläggare
ContentlblSeverity = Felkategori
ContentlblUserInput = Angiven input
ContenttblInfo = Uppdatera enbart de filer du vet att du ändrat själv
ContenttblUpdatedInProd = Dessa har uppdaterats i produktion, men inte i dev.
ContenttiErrorLogs = Felloggar
ContenttiLogs = Loggar
ContenttiRollback = Rollbackmachine
ContenttiUpdated = Uppdaterade
ContenttiUpdatedInProd = Uppdaterade i prod
ContenttiUpdates = Uppdateringar
ContentWindow = Skript Administration
StrErrorlogsNotLoaded = Felloggar har inte lästs in
StrLogIntro = Uppdaterat
StrNewDataFile = Ny PS datafil
StrNewGuiFile = Ny GUI-fil
StrNewLocFile = Ny localization-fil
StrNewOtherFile = Ny fil
StrNewScript = Nytt skript
StrNoUpdates = Inga uppdaterade filer
StrRollbackDone = Fil tillbakarullad
StrRollbackName = uppdaterad
StrRollbackPahNotFound = Filen hittas inte i produktion. Denna fil har troligen ersatts av annan fil, eller döpts om. Filen bör därför inte rullas tillbaka.
StrRollbackVerification = Vill du ersätta filen i produktion med denna fil?
StrRollbackVerificationDate = Filversion att rulla tillbaka:
StrRollbackVerificationPath = Fil att ersätta:
StrScanSummary = i fas
StrScriptState = Tillhörande skript i
StrSplReadErrorLogs = Läser felloggar
StrSplReadLogs = Läser logfiler
StrSummaryUp = filer uppdaterade
StrUpdates = uppdaterade filer
StrUpdatesInProd = filer har ändrats i produktion, men inte i dev
'@
