ConvertFrom-StringData @'
ContentbtnListRollbacks = Lista rollbacks
ContenttiRollback = Rollbackmachine
ContentdgRollbacksColDate = Fildatum
ContentdgRollbacksColUpdatedBy = Uppdaterad av
StrSplReadLogs = Läser logfiler
StrSplReadErrorLogs = Läser felloggar
StrErrorlogsNotLoaded = Felloggar har inte lästs in
ContentbtnDoRollback = Rulla tillbaka filversion
ContentbtnOpenRollbackFile = Öppna fil
StrRollbackVerification = Vill du ersätta filen i produktion med denna fil?
StrRollbackVerificationPath = Fil att ersätta:
StrRollbackVerificationDate = Filversion att rulla tillbaka:
StrRollbackPahNotFound = Filen hittas inte i produktion. Denna fil har troligen ersatts av annan fil, eller döpts om. Filen bör därför inte rullas tillbaka.
StrRollbackDone = Fil tillbakarullad
ContentbtnCheckForUpdates = Sök efter uppdateringar
ContentbtnReadErrorLogs = Läs in felloggar
ContentbtnReadLogs = Läs in loggar
ContentbtnOpenErrorLog = Öppna fellogg
ContentbtnUpdateScripts = Uppdatera markerade filer
ContenttblInfo = Uppdatera enbart de filer du vet att du ändrat själv
ContenttblUpdatedInProd = Dessa har uppdaterats i produktion, men inte i dev.
ContenttiErrorLogs = Felloggar
ContentgbErrorInfo = Information om felmeddelandet
ContentlblErrorMessage = Fel meddelande
ContentlblOperator = Handläggare
ContentlblSeverity = Felkategori
ContentlblUserInput = Angiven input
ContenttiLogs = Loggar
ContenttiUpdated = Uppdaterade
ContenttiUpdatedInProd = Uppdaterade i prod
ContenttiUpdates = Uppdateringar
ContentdgErrorLogsColLogDate = Loggningstid
ContentdgLogsColLogDate = Loggningstid
ContentdgLogsColLogText = Loggtext
ContentdgLogsColUserInput = Angiven input
ContentdgLogsColSuccess = Framgång
ContentdgLogsColErrorlogDate = Fellogg
ContentdgLogsColOutputFile = Utfil
ContentdgLogsColOperator = Handläggare
ContentdgUpdatesColName = Namn
ContentdgUpdatesColPath = Sökväg
ContentdgUpdatesColDevUpd = Uppdaterad i development
ContentdgUpdatesColProdUpd = Uppdaterad i produktion
ContentdgUpdatesColProdState = Utvecklingsfas
ContentWindow = Skript Administration
ScriptContentInDev = Dev
StrDevTooltip = Under utveckling
StrLogIntro = Uppdaterat
StrNewDataFile = Ny PS datafil
StrNewGuiFile = Ny GUI-fil
StrNewLocFile = Ny localization-fil
StrNewOtherFile = Ny fil
StrNewScript = Nytt skript
StrNoUpdates = Inga uppdaterade filer
StrRollbackName = uppdaterad
StrScanSummary = i fas
StrScriptInDevTooltip = Skriptfil under utveckling
StrScriptState = Tillhörande skript i
StrSelectAll = Markera alla
StrSummaryDev = under utveckling
StrSummaryUp = filer uppdaterade
StrUpdates = uppdaterade filer
StrUpdatesInProd = filer har ändrats i produktion, men inte i dev
StrUpInDev = dev uppdaterad
StrUpInProd = prod uppdaterad
'@
