ConvertFrom-StringData @'
CodeRegExDomain = @test.com$
ContentbtnAddAdmin = Add
ContentbtnAddMember = Add
ContentbtnCheck = Check
ContentbtnCopyUsers = Copy
ContentbtnFetchAdmins = Get administrators
ContentbtnFetchMembers = Get members
ContentbtnRemoveMembersAzure = Remove member in Azure
ContentbtnRemoveMembersExchange = Remove member in Exchange
ContentbtnRemoveSelectedAdmins = Remove
ContentbtnReset = Reset
ContentbtnSMAddress = Change address
ContentbtnSMName = Change name
ContentbtnSMOwner = Change owner
ContentbtnSyncToExchange = Start sync
ContentcbAddMemberLoc = Azure, Exchange, Both
ContentcbAddMemberPerm = Read permission, Full permission
ContentdgAdminsMailTitle = Emailaddress
ContentdgAdminsNameTitle = Name
ContentdgMembersMailTitle = Emailaddress
ContentdgMembersNameTitle = Name
ContentdgMembersPermissionTitle = Permissionrtype
ContentdgSuggestionsColDispName = Displayname
ContentdgSuggestionsColPrimSmtp = Mailaddress
ContentexpAddAdmin = Add administrator
ContentexpAddMembers = Add member
ContentgAddAdmin = New administrator
ContentgMembersAzure = Members according to Azure
ContentgMembersExchange = Members according to Exchange
ContentgRemoveSelectedAdmins = Remove administrators
ContentlblAddAdmin = Enter new administrator
ContentlblAddMember = Enter userid or emailaddress
ContentlblAddMemberLoc = Add to:
ContentlblAddMemberPerm = Permissiontype:
ContentlblCopyUsers = Copy members and administrators
ContentlblRemoveSelectedAdmins = Remove selected administrators
ContentlblSM = Enter name or emailaddress for the shared mailbox
ContentlblSMAddress = Primary SMTP address
ContentlblSMName = Name
ContentlblSMOwner = Owner
ContentlblSMOwnerAddr = Emailaddress
ContentlblSMOwnerId = User id
ContentlblSuggestionsTitle = Several sharedmailboxes were found that match the search term. Select one by double-clicking
ContentlblSyncToExchange = Start a sync of users to Exchange
ContentOwnerAddrTT = This field is locked and cannot be changed. Instead, enter the ID of the person to be specified as the owner
ContenttiAdmins = Administrators
ContenttiInfo = Info
ContenttiMembers = Members
ErrLogNewAdm = New admin
ErrLogNewMem = New member
ErrLogNewNameAddrGetGrps = Set new name / address (Get groups)
ErrLogNewNameAddrSetAzGrps = Set new name / address (Set Azure groups)
ErrLogNewNameAddrSetMailbox = Set new name / address (Set mailbox)
ErrLogNewOwner = Add new owners
ErrLogRemoveAdm = Remove admin
ErrLogRemoveMemAzGrp = Remove Azure permission
ErrLogRemoveMemGSOBT = Remove authorization to send as an agent
ErrLogRemoveMemPermExc = Remove the Exchange permission
ErrLogSearchMailbox = Search of mailbox
ErrLogSyncFull = Synchronizes full permissions
ErrLogSyncRead = Synchronizes read permissions
ErrMsgAdAccNotActive = AD account is not active, the person may have quit
ErrMsgNoAdAccount = AD account does not exist
ErrMsgNoMailAccount = Can't find active mail account with this address
ErrMsgNoOwner = No owner specified
ErrMsgOwnerAdDisabled = User is not active in AD
ErrMsgOwnerAdError = An error occurred while searching AD
ErrMsgOwnerAdNotFound = Can't find any user with the specified ID
LogNewAdm = New admin
LogNewMember = New member
LogNewMemberUILoc = Service:
LogNewMemberUIPerm = Permission:
LogNewMemberUIUser = User:
LogNewNameAddr = New name/address
LogNewNameAddrUIAddr = Mailaddress:
LogNewNameAddrUIName = Name:
LogNewOwner = New owner
LogRemoveAdm = Remove admin
LogRemoveMemAz = Remove Azure permission
LogRemoveMemExc = Remove the Exchange permission
LogSearchMailbox = Search of mailbox
LogSync = Started synchronization
StrAzureADGrpNameAdmSuffix = -Admin
StrAzureADGrpNameFullSuffix = -Full
StrAzureADGrpNamePrefix = MB-
StrAzureADGrpNameReadSuffix = -Read
StrConfirmNewOwner = change owner of the shared mailbox
StrConfirmPrefix = You are about to
StrConfirmRemoveMembers = users are about to be removed in
StrConfirmRename = change name of shared mailbox
StrConfirmSuffix = Are you sure you want to continue?
StrGettingAdmins = Retrieving administrators
StrGettingMailbox = Retrieves sharedmailbox
StrGettingMembers = Retrieving members
StrNameOrAddrNotUpd = When changing name or emailaddress, this change needs to be reflected in the other value. This does not appears to have happened. Do you want to use the values in the textboxes as new values for the shared mailbox?
StrNoAdmins = <No administrators specified in Azure>
StrNoUpdate = The shared mailbox was not updated
StrOwnerAttrPrefix = Owner:
StrPermFull = Full permission
StrPermRead = Read permission
StrPermSend = Permission to send on behalf of
StrPermSendOnBehalf = Can send on behalf of
StrUsersCopied = Users have been copied to 
'@
