ConvertFrom-StringData @'
ContentBtnPerform = Utför
ContentBtnUndo = Avbryt
ContentTblApp = Välj applikation
ContentTblAppGroupList = Välj app-grupp genom att dubbelklicka
ContentTblGroupsChosen = Valda app-grupper
ContentTblLog = Utförda ändringar
ContentTblUsersAddPermission = Skapa behörighet
ContentTblUsersRemovePermission = Ta bort behörighet
ContentWindowTitle = Ta bort/lägg till app-behörigheter
ErrMessageGetAppGroups = Hämtning av appgrupper
ErrMessageGetUser = Hämta användare
ErrMessageSetPassword = Sätta lösenord
ErrMessageSetSettings = Ställ in inställningar
ErrScriptPermissions = Du saknar nödvändiga rättigheter för att köra detta skript
LogInputAdd = För tillägg: 
LogInputRemove = För borttag:
LogMessageAdd = Har fått behörighet:
LogMessageRemove = Tagit bort behörighet:
MsgMessageIntro = Har utfört nedan ändringar till följande
MsgNew = Ny behörighet
MsgNewPassword = nytt lösenord
MsgNoAccount = Hittade inget konto för följande
MsgRemove = Ta bort behörighet
QCont1 = Vill du för
QCont2 = utföra
QCont3 = ändringar
QContErr = Vissa användare har inte AD-konton
QContTitle = Fortsätta
StrAddedUsersTitle = Tillagd behörighet
StrBORoleGrp = Role_Servicedesk_BO
StrDuplicates = Det finns dubbletter av värden i listorna. Rätta till dessa och kör igen
StrDuplicatesTitle = Dubbletter
StrErrorUsersTitle = ID saknas i AD
StrFinishMessage = ändringar gjorda. Ett lösningsmeddelande har kopierats till clipboard
StrFinishMessageTitle = Klar
StrGetADGroups = Hämtar app-grupper...
StrGettingUser = Hämtar användare
StrGroupsTitle = Grupper
StrLogMessage = Applikation
StrLogOut = För att behörigheten ska börja gälla, behöver kontot loggas ut och sedan in igen.
StrOpGrp = Role_OP
StrOpLogPath = \\\\domain.test.com\\Results\\FolderTool
StrPreparing = Förbereder...
StrProgressTitle = Tillämpar gruppbehörigheter
StrRemovedUsersTitle = Behörighet borttagen
StrSigGen = Med vänliga hälsningar
StrSigSD = IT, Servicedesk
StrSpecOrg = org7
'@
