ConvertFrom-StringData @'
ContentbtnPerform = Utför
ContentbtnUndo = Avbryt
ContentlblApp = Välj applikation
ContentlblAppGroupList = Välj app-grupp genom att dubbelklicka
ContentlblGroupsChosen = Valda app-grupper
ContentlblLog = Utförda ändringar
ContentlblUsersAddPermission = Skapa behörighet
ContentlblUsersRemovePermission = Ta bort behörighet
ContentWindowTitle = Ta bort/lägg till app-behörigheter
ErrMessageGetAppGroups = Hämtning av appgrupper
ErrMessageGetUser = Hämta användare
ErrMessageSetPassword = Sätta lösenord
ErrMessageSetSettings = Ställ in inställningar
ErrScriptPermissions = Du saknar nödvändiga rättigheter för att köra detta skript
LogInputAdd = För tillägg: 
LogInputRemove = För borttag:
LogMessageAdd = Har fått behörighet:
LogMessageRemove = Tagit bort behörighet:
LogNew = Ny behörighet
LogNoAccount = Hittade inget konto för följande
LogRemove = Ta bort behörighet
MsgMessageIntro = Har utfört nedan ändringar till följande
MsgNew = Ny behörighet
MsgNewPassword = nytt lösenord
MsgNoAccount = Hittade inget konto för följande
MsgRemove = Ta bort behörighet
QCont1 = Vill du för
QCont2 = utföra
QCont3 = ändringar
QContErr = Vissa användare har inte AD-konton
QContTitle = Fortsätta
StrBORoleGrp = Role_Servicedesk_BO
StrDuplicates = Det finns dubbletter av värden i listorna. Rätta till dessa och kör igen
StrDuplicatesTitle = Dubbletter
StrFinishMessage = ändringar gjorda. Ett lösningsmeddelande har kopierats till clipboard
StrFinishMessageTitle = Klar
StrGetADGroups = Hämtar app-grupper...
StrGettingUser = Hämtar användare
StrLogMessage = Applikation
StrOpGrp = Role_OP
StrOpLogPath = \\\\domain.test.com\\Results\\FolderTool
StrPreparing = Förbereder...
StrProgressTitle = Tillämpar gruppbehörigheter
StrSigGen = Med vänliga hälsningar
StrSigSD = IT, Servicedesk
StrSpecOrg = org7
'@
