ConvertFrom-StringData @'
CodeIdMatch = doms
CodeIdRegEx = ^dom(kat|sys)\w{4}
ContentbtnActivate = Aktivera konto
ContentbtnCancel = Avbryt
ContentbtnExtend = Förläng giltighetstid för lösenord
ContentbtnUnlock = Lås upp konto
ContentlblID = Ange Id eller kontonamn
ContentWindow = AD-konto kontroll
ErrActivate = Error - Aktivering
ErrExtendPassword = Error - Förlängning av giltighet för lösenord
ErrMessageActivate = Kunde inte aktivera konto. Felmeddelande
ErrLExtendPassword = Kunde inte förlänga giltighetstiden på lösenordet. Felmeddelande
ErrLogActivate = Aktivering av konto
ErrLogExtendPassword = Förlängning av giltighet för lösenord. Felmeddelande
ErrLogUnlock = Upplåsning av konto. Felmeddelande
ErrLUnlock = Kunde inte låsa upp konto. Felmeddelande
ErrMessageActivatePermission = Vissa konton, t.ex. gaisys konton, kan endast aktiveras av Driften
ErrMessageExtendPasswordPermission = Vissa konton, t.ex. gaisys konton, kan endast hanteras av Driften.
ErrMessageUnlockPermission = Vissa konton, t.ex. gaisys konton, kan endast låsas upp av Driften
ErrUnlock = Error - Upplåsning av konto
WActivate = Aktiverad
WActiveUser = Kontostatus: Kontot är aktivt (enabled) och upplåst
WBlockedUser = Kontostatus: Kontot är inaktiverat och SKA INTE AKTIVERAS! Lägg ärendet till Driften
WDescText = DENNA ANVÄNDARE SKA INTE AKTIVERAS, KONTAKTA KATALOG FÖR MER INFO
WDisabledUser = Kontostatus: Kontot är inaktiverat (disabled): För att aktivera kontot, se Knowledge 'AD-konto har blivit Disabled/Inaktiverat'
WExpiredPassword = Lösenordsstatus: Lösenordet är över 200 dagar gammalt och har gått ut. Förläng giltighetstiden för det befintliga lösenordet med 'Förläng lösenord'-knappen nedan. Lösenordet gick ut
WFutureExpiry = Lösenordsstatus: Lösenordet går ut
WLActivate = Kontot aktiverat.
WLActiveUser = Aktivt
WLBlockedUser = inaktivt > Driften
WLDisabledUser = inaktivt
WLExpiredPassword = giltighet lösenord passerad
WLFutureExpiry = aktivt lösenord
WLLockedUser = låst
WLManualExpiry = manuell giltighetstid > Driften
WLManualExpiryEnded = manuell giltighetstid passerad > Driften
WLNeverEndingPassword = oändligt lösenord
WLockedUser = Kontot är låst (locked) p.g.a. för många felaktiga inloggningsförsök, se Knowledge 'AD-kontot är låst'
WLPasswordChange = lösenordsbyte vid nästa inloggning
WLPasswordExtended = Giltighetstiden för lösenordet har förlängts.
WLUnlocked = Kontot har låsts up.
WManualExpiry = Giltighetstid: Kontot har ett manuellt giltighetsdatum (Account expires). Kontot hanteras av Driften. Giltighetstiden går ut
WManualExpiryEnded = Giltighetstid: Kontot har ett manuellt giltighetsdatum som passerat (Account expires datumet har passerat). Lägg ärendet till Driften. Kontot gick ut
WNeverEndingPassword = Lösenordsstatus: Lösenordet går aldrig ut
WNotFoundInAd = hittas inte i AD
WPasswordChange = Lösenordsstatus: Ett lösenordsbyte ligger uppköat ('User must change password at next logon' är förbockat). Be användaren logga in med det nya lösenordet som de nyligen borde fått. Alternativt sätt ett nytt lösenord åt användaren (Följ Knowledge för lösenordsbyte i AD enligt användarens organisationstillhörighet).
WPasswordExtended = Giltighet för lösenord förlängd
WReadUser = Inläst användare
WUnlocked = Upplåst
'@
