ConvertFrom-StringData @'
CodeIdMatch = doms
CodeLockedLogsLocation = \\\\loc.test.se\\LockedoutLogs$
CodeOuSpecDep = OU=SpecDep,DC=Org,DC=se
CodeShareAccMatch = f(org3)|(org2)|(org1)
ContentbtnActivate = Aktivera konto
ContentbtnCancel = Avbryt
ContentBtnListLocked = Lista låsningar
ContentbtnUnlock = Lås upp konto
ContentDgLockedListHeader0 = Tid
ContentDgLockedListHeader1 = Dator
ContentDgLockedListHeader2 = Domänkontrollant
ContentlblID = Ange id eller kontonamn
ContentLblLockedList = Låsning av konto har skett vid dessa datorer
ContentWindow = AD-konto kontroll
ErrLogActivate = Aktivering av konto
ErrLogExtendPassword = Förlängning av giltighet för lösenord. Felmeddelande
ErrLogUnlock = Upplåsning av konto. Felmeddelande
ErrMsgActivate = Kunde inte aktivera konto. Felmeddelande
ErrMsgActivatePermission = Du har ej behörighet att aktivera detta konto, se rutin för mer info
ErrMsgActivatePermissionSpecDep = Användaren tillhör SpecDep, hänvisa till SpecIT som aktiverar (Se rutin)
ErrMsgExtendPassword = Kunde inte förlänga giltighetstiden på lösenordet. Felmeddelande
ErrMsgExtendPasswordPermission = Du har ej behörighet att förlänga giltighetstiden på lösenordet för detta konto, se rutin för mer info om vem som kan låsa upp det
ErrMsgExtendPasswordPermissionSpecDep = Användaren tillhör SpecDep, hänvisa till SpecIT som kan förlänga giltighetstiden för lösenordet (Se rutin)
ErrMsgUnlock = Kunde inte låsa upp konto. Felmeddelande
ErrMsgUnlockPermission = Du har ej behörighet att låsa upp detta konto, se rutin för mer info om vem som kan låsa upp det
ErrMsgUnlockPermissionSpecDep = Användaren tillhör SpecDep, hänvisa till SpecIT som låser upp kontot (Se rutin)
LogActivated = Aktiverad
LogBlockedUser = inaktivt > Driften
LogDisabledUser = inaktivt
LogErrActivate = Error - Aktivering
LogErrExtendPassword = Error - Förlängning av giltighet för lösenord
LogErrUnlock = Error - Upplåsning av konto
LogExpiredPassword = giltighet lösenord passerad
LogFutureExpiry = aktivt lösenord
LogLocked = låst
LogLockedLookUp = Listade låsningar
LogManualExpiry = manuell giltighetstid > driften
LogManualExpiryEnded = manuell giltighetstid passerad > driften
LogNeverEndingPassword = oändligt lösenord
LogPasswordChange = lösenordsbyte vid nästa inloggning
LogPasswordExtended = Giltighet för lösenord förlängd
LogUnlocked = Upplåst
StrActivated = Kontot aktiverat.
StrActive = Aktivt
StrDoNotActivate = DENNA ANVÄNDARE SKA INTE AKTIVERAS, KONTAKTA DRIFTEN FÖR MER INFO
StrExpiredPassword = Lösenordsstatus: Lösenordet är över 200 dagar gammalt och har gått ut. Förläng giltighetstiden för det befintliga lösenordet med 'Förläng lösenord'-knappen nedan. Lösenordet gick ut
StrFutureExpiry = Lösenordsstatus: Lösenordet går ut
StrLocked = Kontot är låst (locked) p.g.a. för många felaktiga inloggningsförsök, se rutin
StrManualExpiry = Giltighetstid: Kontot har ett manuellt giltighetsdatum (Account expires). Kontot hanteras av driften. Giltighetstiden går ut
StrManualExpiryEnded = Giltighetstid: Kontot har ett manuellt giltighetsdatum som passerat (Account expires datumet har passerat). Lägg ärendet till driften. Kontot gick ut
StrNeverEndingPassword = Lösenordsstatus: Lösenordet går aldrig ut
StrNotFoundInAd = hittas inte i AD
StrPasswordChange = Lösenordsstatus: Ett lösenordsbyte ligger uppköat ('User must change password at next logon' är förbockat). Be användaren logga in med det nya lösenordet som de nyligen borde fått. Alternativt sätt ett nytt lösenord åt användaren (Följ rutin för lösenordsbyte i AD enligt användarens organisationstillhörighet).
StrPasswordExtended = Giltighetstiden för lösenordet har förlängts.
StrReadUser = Inläst användare
StrSharedAccWorkstation = Funktionskontot är kopplat till: 
StrUnlocked = Kontot har låsts up.
StrUserActive = Kontostatus: Kontot är aktivt (enabled) och upplåst
StrUserBlocked = Kontostatus: Kontot är inaktiverat och SKA INTE AKTIVERAS! Lägg ärendet till driften
StrUserDisabled = Kontostatus: Kontot är inaktiverat (disabled): För att aktivera kontot, se rutin
'@
