ConvertFrom-StringData @'
CodeIdMatch = doms
CodeOuSpecDep = OU=SpecDep,DC=Org,DC=se
ContentbtnActivate = Aktivera konto
ContentbtnCancel = Avbryt
ContentbtnExtend = Förläng giltighetstid för lösenord
ContentbtnUnlock = Lås upp konto
ContentlblID = Ange Id eller kontonamn
ContentWindow = AD-konto kontroll
ErrLogActivate = Aktivering av konto
ErrLogExtendPassword = Förlängning av giltighet för lösenord. Felmeddelande
ErrLogUnlock = Upplåsning av konto. Felmeddelande
ErrMsgActivate = Kunde inte aktivera konto. Felmeddelande
ErrMsgActivatePermission = Du har ej behörighet att aktivera detta konto, se rutin för mer info
ErrMsgActivatePermissionSpecDep = Användaren tillhör SpecDep, hänvisa till Lab som aktiverar (Se rutin)
ErrMsgExtendPassword = Kunde inte förlänga giltighetstiden på lösenordet. Felmeddelande
ErrMsgExtendPasswordPermission = Du har ej behörighet att förlänga giltighetstiden på lösenordet för detta konto, se rutin för mer info om vem som kan låsa upp det
ErrMsgExtendPasswordPermissionSpecDep = Användaren tillhör SpecDep, hänvisa till Lab som kan förlänga giltighetstiden för lösenordet (Se rutin)
ErrMsgUnlock = Kunde inte låsa upp konto. Felmeddelande
ErrMsgUnlockPermission = Du har ej behörighet att låsa upp detta konto, se rutin för mer info om vem som kan låsa upp det
ErrMsgUnlockPermissionSpecDep = Användaren tillhör SpecOp, hänvisa till Lab som låser upp kontot (Se rutin)
LogActivated = Aktiverad
LogBlockedUser = inaktivt > Katalog
LogDisabledUser = inaktivt
LogErrActivate = Error - Aktivering
LogErrExtendPassword = Error - Förlängning av giltighet för lösenord
LogErrUnlock = Error - Upplåsning av konto
LogExpiredPassword = giltighet lösenord passerad
LogFutureExpiry = aktivt lösenord
LogLocked = låst
LogManualExpiry = manuell giltighetstid > Katalog
LogManualExpiryEnded = manuell giltighetstid passerad > Katalog
LogNeverEndingPassword = oändligt lösenord
LogPasswordChange = lösenordsbyte vid nästa inloggning
LogPasswordExtended = Giltighet för lösenord förlängd
LogUnlocked = Upplåst
StrActivated = Kontot aktiverat.
StrActive = Aktivt
StrDoNotActivate = DENNA ANVÄNDARE SKA INTE AKTIVERAS, KONTAKTA KATALOG FÖR MER INFO
StrExpiredPassword = Lösenordsstatus: Lösenordet är över 200 dagar gammalt och har gått ut. Förläng giltighetstiden för det befintliga lösenordet med 'Förläng lösenord'-knappen nedan. Lösenordet gick ut
StrFutureExpiry = Lösenordsstatus: Lösenordet går ut
StrLocked = Kontot är låst (locked) p.g.a. för många felaktiga inloggningsförsök, se rubrik 'Kontot är låst' i rutin
StrManualExpiry = Giltighetstid: Kontot har ett manuellt giltighetsdatum (Account expires). Kontot hanteras av Katalog. Giltighetstiden går ut
StrManualExpiryEnded = Giltighetstid: Kontot har ett manuellt giltighetsdatum som passerat (Account expires datumet har passerat). Lägg ärendet till Katalog. Kontot gick ut
StrNeverEndingPassword = Lösenordsstatus: Lösenordet går aldrig ut
StrNotFoundInAd = hittas inte i AD
StrPasswordChange = Lösenordsstatus: Ett lösenordsbyte ligger uppköat ('User must change password at next logon' är förbockat). Be användaren logga in med det nya lösenordet som de nyligen borde fått. Alternativt sätt ett nytt lösenord åt användaren (Följ rutin för lösenordsbyte i AD enligt användarens organisationstillhörighet).
StrPasswordExtended = Giltighetstiden för lösenordet har förlängts.
StrReadUser = Inläst användare
StrUnlocked = Kontot har låsts up.
StrUserActive = Kontostatus: Kontot är aktivt (enabled) och upplåst
StrUserBlocked = Kontostatus: Kontot är inaktiverat och SKA INTE AKTIVERAS! Lägg ärendet till Katalog
StrUserDisabled = Kontostatus: Kontot är inaktiverat (disabled): För att aktivera kontot, se rubrik 'Konto har blivit Disabled/Inaktiverat' i artikel: AD - Låst konto
'@
