ConvertFrom-StringData @'
ContentBtnAbort = Avbryt
ContentBtnCreateQuestion = Kopiera fråga om hjälp, till Katalog
ContentBtnOpenFolder = Öppna mapp
ContentBtnOpenFolderTT = Öppna mappen filen är placerad i
ContentBtnOpenSummary = Öppna fil
ContentBtnPrep = Förbered sökning
ContentBtnReset = Återställ
ContentBtnRunVirusScan = Kör virusscan
ContentBtnSearchExt = Sök filändelse
ContentBtnSearchExtTT = Sök på filändelse på Google
ContentBtnSearchFileName = Sök filnamn
ContentBtnSearchFileNameTT = Sök på filnamnet på Google
ContentBtnStartSearch = Starta sökning
ContentCbSetAccountDisabled = Inaktivera kontot
ContentLvColumnCreated = Skapad
ContentLvColumnName = Namn
ContentLvColumnOwner = Ägare
ContentLvColumnSize = Storlek
ContentLvColumnUpdated = Uppdaterad
ContentRbAllToolTip = Hämtar alla filer, med ändring gjord senaste 60 dagarna. Vid sökning för alla filer, kan det ta betydligt längre tid.
ContentRbLatestToolTip = Hämtar de filer som blivit ändrade inom de senaste två veckorna
ContentRbPrevDateToolTip = Hämtar filer som ändrats efter angivet datum
ContentTblCaseNrTitle = Ange ärendenummer
ContentTblCbExpandGroups = Expandera alla filtyps-grupper
ContentTblCbGroupExtensions = Gruppera filer per filtyp
ContentTblFileCountTitle = Totalt antal filer:
ContentTblFilterMatch = Filer som matchar angivet filter
ContentTblFolderCountTitle = Antal mappar som genomsöks:
ContentTblFolderListTitle = Väntar på fillista från följande mappar
ContentTblGroupInputTitle = Inställningar
ContentTblGroupSearchSettingsTitle = Sökinställningar
ContentTblGroupSummaryTitle = Sammanfattning
ContentTblIdTitle = Ange id för användare
ContentTblMDG = Filer med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentTblMDH = Filer i H-mappen med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentTblO = Mappar du inte har behörighet till, lägg ärende till katalog
ContentTblPrevDateText = Från och med angivet datum
ContentTblRbAllText = Sök alla filer
ContentTblRbLatest = Senaste två veckorna
ContentTblSummaryTitle = Sammanfattning skriven till:
ContentTblUserTitle = Användare:
ContentTblValuesTitle = Båda värden måste anges
ContentTiFilesHeader = Alla filer
ContentTiFilterMatchHeader = Matchar filter
ContentTiMDGHeader = Multipla filändelser på G:
ContentTiMDHHeader = Multipla filändelser på H:
ContentTiOHeader = Mappar du saknar behörighet till
LogScannedFile = Körde virusscan
LogScannedFileTitle = Filnamn
MsgRecycleBin = Filen ligger i Papperskorgen och kan inte kontrolleras.
StrDescSplit = på
StrEnableUser = Ska användarkontot aktiveras?
StrErrUserNotFound = ingen användare med det id:t
StrFileOwner = Användaren
StrFileSearchFinished = Finished searching for files
StrLogMsgCaseNr = Ärendenummer
StrLogMsgFileSearchAborted = Avbröt filsökning
StrLogMsgFilesMatchingFilterCount = Antal filer som matchar angivet filter:
StrLogMsgFilesScannedForVirus = Dessa filer har kontrollerats med antivirus
StrLogMsgFilesWithDoubleExtG = Antal filer med eventuellt dubbla filändelser på G:
StrLogMsgFilesWithDoubleExtH = Antal filer med eventuellt dubbla filändelser på H:
StrLogMsgFolderSearch = Söker mappar
StrLogMsgId = Användar-id
StrLogMsgOpenFolder = Öppnade mapp
StrLogMsgOtherPermCount = Antal mappar där behörighet saknades:
StrLogMsgSearchExt = Sökte på filändelse
StrLogMsgSearchFileName = Sökte på filnamn
StrLogMsgSearchTime = Sökningstid
StrLogMsgTotNumFiles = Totalt antal filer
StrLogQuestionCopied = Kopierat
StrLogScriptStart = Start
StrMultiFileVirusSearch = Flertalet filer har valts, vilket kommer ta längre tid, ju fler filer som valts
StrNoExtension = <Ingen filändelse>
StrNoFilesFound = < Inga filer hittades >
StrOPFilteringFolders = Filtrerar funna mappar
StrOPGettingFiles = Startar hämtning av filer
StrOPGettingFolders = Hämtar mappar
StrOPWaitGettingFiles = Väntar hämtning av filer
StrOutput1 = Sökning av potentiella virus
StrOutput2 = Användare
StrOutput3 = Ärendenummer
StrOutput4 = Totalt antal filer:
StrOutputTimeline1 = Sökte: Filer uppdaterade senaste två veckorna
StrOutputTimeline2 = Sökte: Filer uppdaterade efter datum
StrOutputTimeline3 = Sökte: Alla tillgängliga filer
StrOutputTitleAllFiles = Alla funna filer
StrOutputTitleFilterMatch = Dessa filer matchade filter
StrOutputTitleFilterMatch2 = Angivet filter:
StrOutputTitleFolders = Genomsökta mappar
StrOutputTitleFoldersOtherPerm = Saknade behörighet för följande mappar
StrOutputTitleMultiDotG = Multipla filändelser G:
StrOutputTitleMultiDotH = Multipla filändelser H:
StrQuestion1 = har anmält eventuellt virus i ärende
StrQuestion2 = Mappar under H:\\ samt G:\\ har undersökts, men det saknas behörighet för mapparna nedan.
StrQuestion3 = Kan ni hjälpa till att titta på dessa?
StrQuestionCopied = Text har kopierats till clipboard
StrUserAccountAlreadyLocked = Kontot redan inaktiverat
StrWaitingFileSearch = <Väntar att filsökning ska startas>
StrVerbVirusScan = Sök efter hot
'@
