ConvertFrom-StringData @'
ContentbtnAbort = Avbryt
ContentbtnCreateQuestion = Kopiera fråga om hjälp, till Katalog
ContentbtnOpenFolder = Öppna mapp
ContentbtnOpenFolderTT = Öppna mappen filen är placerad i
ContentbtnOpenSummary = Öppna fil
ContentbtnPrep = Förbered sökning
ContentbtnReset = Återställ
ContentbtnRunVirusScan = Kör virusscan
ContentbtnSearchExt = Sök filändelse
ContentbtnSearchExtTT = Sök på filändelse på Google
ContentbtnSearchFileName = Sök filnamn
ContentbtnSearchFileNameTT = Sök på filnamnet på Google
ContentbtnStartSearch = Starta sökning
ContentcbExpandGroups = Expandera alla filtyps-grupper
ContentcbSetAccountDisabled = Inaktivera kontot
ContentgbDatePicker = Datum för äldsta ändring av fil
ContentgbInfo = Sammanfattning
ContentgbSearch = Sökinställningar
ContentgbSettings = Inställningar
ContentlblCaseNrTitle = Ange ärendenummer
ContentlblFileCountTitle = Totalt antal filer:
ContentLblFiles = Listar alla filer i mappar användaren har behörighet till.
ContentLblFiles2W = Listar alla filer uppdaterade de senaste två veckorna, i mappar användaren har behörighet till.
ContentlblFilterMatch = Filer som matchar angivet filter
ContentlblFolderCountTitle = Antal mappar som genomsöks:
ContentlblFolderListTitle = Väntar på fillista från följande mappar
ContentlblIDTitle = Ange HSA-id för användare
ContentlblMDG = Filer med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentlblMDH = Filer i H-mappen med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentlblO = Mappar du inte har behörighet till, lägg ärende till katalog
ContentlblSummaryTitle = Sammanfattning skriven till:
ContentlblUserTitle = Användare:
ContentlblValuesTitle = Båda värden måste anges:
ContentlvColumnCreated = Skapad
ContentlvColumnName = Namn
ContentlvColumnUpdated = Uppdaterad
ContentrbAll = Sök alla filer
ContentrbAllToolTip = Hämtar alla filer, med ändring gjord senaste 60 dagarnad. Vid sökning för alla filer, kan det ta betydligt längre tid.
ContentrbLatest = Senaste två veckorna
ContentrbLatestToolTip = Hämtar de filer som blivit ändrade inom de senaste två veckorna
ContentrbPrevDateToolTip = Hämtar filer som ändrats efter angivet datum
ContenttbPrevDateText = Från och med angivet datum
ContenttiFilesHeader = Alla filer
ContenttiFilterMatchHeader = Matchar filter
ContenttiMDGHeader = Multipla filändelser på G:
ContenttiMDHHeader = Multipla filändelser på H:
ContenttiOHeader = Mappar du saknar behörighet till
ErrInvalidCaseNr = Ett giltigt ärendenummer måste anges.
ErrInvalidID = Inget konto hittades med angivet HSA-id.
ErrLogInvalidId = Inget användarkonto hittades med angivet HSA-id
LogScannedFile = Körde virusscan
LogScannedFileTitle = Filnamn
StrDescSplit = på
StrEnableUser = Ska användarkontot aktiveras?
StrErrUserNotFound = ingen användare med det id:t
StrFileSearchFinished = Finished searching for files
StrLogMsgCaseNr = Ärendenummer
StrLogMsgFileSearchAborted = Avbröt filsökning
StrLogMsgFilesMatchingFilterCount = Antal filer som matchar angivet filter:
StrLogMsgFilsWithDoubleExtG = Antal filer med eventuellt dubbla filändelser på G:
StrLogMsgFilsWithDoubleExtH = Antal filer med eventuellt dubbla filändelser på H:
StrLogMsgFolderSearch = Söker mappar
StrLogMsgId = Användar-id
StrLogMsgOpenFolder = Öppnade mapp
StrLogMsgOtherPermCount = Antal mappar där behörighet saknades:
StrLogMsgSearchExt = Sökte på filändelse
StrLogMsgSearchFileName = Sökte på filnamn
StrLogMsgSearchTime = Sökningstid
StrLogMsgTotNumFiles = Totalt antal filer
StrLogQuestionCopied = Kopierat
StrLogScriptStart = Start
StrMultiFileVirusSearch = Flertalet filer har valts, vilket kommer ta längre tid, ju fler filer som valts
StrNoExtension = <Ingen filändelse>
StrNoFilesFound = < Inga filer hittades >
StrOPFilteringFolders = Filtrerar funna mappar
StrOPGettingFiles = Startar hämtning av filer
StrOPGettingFolders = Hämtar mappar
StrOPWaitGettingFiles = Väntar hämtning av filer
StrOutput1 = Sökning av potentiella virus
StrOutput2 = Användare
StrOutput3 = Ärendenummer
StrOutput4 = Totalt antal filer:
StrOutputTimeline1 = Sökte: Filer uppdaterade senaste två veckorna
StrOutputTimeline2 = Sökte: Filer uppdaterade efter datum
StrOutputTimeline3 = Sökte: Alla tillgängliga filer
StrOutputTitleAllFiles = Alla funna filer
StrOutputTitleFilterMatch = Dessa filer matchade filter
StrOutputTitleFilterMatch2 = Angivet filter:
StrOutputTitleFolders = Genomsökta mappar
StrOutputTitleFoldersOtherPerm = Saknade behörighet för följande mappar
StrOutputTitleMultiDotG = Multipla filändelser G:
StrOutputTitleMultiDotH = Multipla filändelser H:
StrQuestion1 = har anmält eventuellt virus i ärende
StrQuestion2 = Mappar under H:\\ samt G:\\ har undersökts, men det saknas behörighet för mapparna nedan.
StrQuestion3 = Kan ni hjälpa till att titta på dessa?
StrQuestionCopied = Text har kopierats till clipboard
StrUserAccountAlreadyLocked = Kontot redan inaktiverat
StrWaitingFileSearch = <Väntar att filsökning ska startas>
StrVerbVirusScan = Sök efter hot
'@
