ConvertFrom-StringData @'
ContentbtnAddAdmin = Lägg till administratör
ContentbtnAddMember = Lägg till användare
ContentbtnAddRoomlist = Lägg till i markerad rumslista
ContentbtnBookingInfo = Spara
ContentbtnCheck = Hämta
ContentbtnConfirmMessage = Spara ändring
ContentbtnConfirmMessageReset = Återställ meddelande
ContentbtnCopyAdmins = Kopiera administratörer
ContentbtnCopyAll = Kopiera
ContentbtnCopyMembers = Kopiera användare
ContentbtnCopyOtherRoom = Starta kopiering
ContentbtnExport = Exportera
ContentbtnFetchAdmins = Läs in administratörer
ContentbtnFetchMembers = Läs in användare
ContentbtnFetchRLMembership = Hämta medlemskap
ContentbtnLocation = Spara ny plats
ContentbtnRemoveMembersAzure = Ta bort användare i Azure
ContentbtnRemoveMembersExchange = Ta bort användare i Exchange
ContentbtnRemoveRoomlist = Ta bort från markerad rumslista
ContentbtnRemoveSelectedAdmins = Ta bort
ContentbtnReset = Återställ
ContentbtnRoomAddress = Byt adress
ContentbtnRoomName = Byt namn
ContentbtnRoomOwner = Byt ägare
ContentbtnRoomSearch = Sök rum
ContentbtnSelectAll = Markera alla
ContentbtnSyncToExchange = Starta synk
ContentdgAdmColMail = Mailadress
ContentdgAdmColName = Namn
ContentdgAzColMail = Mailadress
ContentdgAzColName = Namn
ContentdgAzColSync = Synkad till Exchange
ContentdgExColMail = Mailadress
ContentdgExColName = Namn
ContentdgExColSync = Finns i Azure
ContentgAddAdmin = Lägg till administratör
ContentgAddMembers = Lägg till medlem
ContentgMembersAzure = Medlemmar enligt Azure
ContentgMembersExchange = Medlemmar enligt Exchange
ContentgRemoveSelectedAdmins = Ta bort administratörer
ContentlblAddAdmin = Ange användare
ContentlblAddMember = Ange användare
ContentlblCheckRoomTitle = Ange rumsnamn
ContentlblCopyAll = Kopiera användare och administratörer
ContentlblExport = Exportera information och användare till Excel-fil
ContentlblLocation = Plats
ContentlblLogTitle = Log
ContentlblRemoveSelectedAdmins = Ta bort markerade administratörer
ContentlblRoomAddress = Adress
ContentlblRoomName = Namn
ContentlblRoomOwner = Ägare
ContentlblRoomOwnerAddr = Adress
ContentlblRoomOwnerID = Id
ContentlblRoomSearchTitle = Ange rum att kopiera behörigheter från:
ContentlblSyncToExchange = Starta synkronisering till Exchange
ContentrbBookingInfoNotPublic = Ej publik
ContentrbBookingInfoPublic = Publik
ContenttblBookingInfo = Ska information om bokningar i rummets kalender vara publikt synlig?
ContenttblRoomListMembership = Medlemskap i följande rumslistor
ContenttiAdmins = Administratörer
ContenttiConfirmMessage = Bekräftelsemeddelande
ContenttiCopyOtherRoom = Kopiera från annat rum
ContenttiInfo = Info
ContenttiListMembership = Medlemskap i rumslista
ContenttiMembers = Medlemmar
ContentttAddNewMembers = Exporten kommer enbart göras för den information som har lästs in. Har t.ex. medlemmar inte hämtats, kommer de inte listas i Excel-filen
ErrAclTooBig = kan inte synkroniseras till Exchange. För många medlemmar i Azure-gruppen.
ErrAclTooBigQuit = kan inte synkroniseras till Exchange. För många medlemmar i Azure-gruppen. Synkroniseringen avslutas.
ErrGen = Problem vid skapande av behörighet i kalendern:
ErrInvalidExternalUserId = finns inte. Personen har troligen slutat.
ErrNotFound = Inget rum hittades
ExcelAdmMailTitle = Mailadress
ExcelAdmTitle = Administratörer
ExcelManUserMailTitle = Mailadress
ExcelManUserTitle = Bokningsbehörighet, ej synkade
ExcelNoAdm = <Inga administratörer angivna>
ExcelNoAdmMail = -
ExcelNoConfirmMess = <Inget bekräftelsemeddelande angivet>
ExcelNoRoomList = <Inte med i någon rumslista>
ExcelNoUser = <Inga användare angivna>
ExcelNoUserMail = -
ExcelRoomConfirmMess = Bekräftelsemeddelande vid bokning
ExcelRoomLocTitle = Plats
ExcelRoomMailTitle = Mailadress
ExcelRoomNameTitle = Rumsnamn
ExcelRoomRoomListTitle = Rumslista
ExcelUserMailTitle = Mailadress
ExcelUserTitle = Bokningsbehörighet
LogAddRoomList = la till i rumslista
LogAdmPerm = Administratörsbehörighet
LogBookInfoNonPub = Book info ej publik
LogBookInfoPub = Book info publik
LogBookingPerm = Bokningsbehörighet
LogCopyOtherRoom = Kopierat behörigheter
LogNewLoc = Ny plats
LogNewResponceMessage = Nytt bekräftelsemeddelande
LogRemRoomList = tog bort från rumslista
LogRemUsersAz = Ta bort anv Az
LogRemUsersEx = Ta bort anv Ex
StrAdminsCopied = Lista över administratörer kopierade
StrAzureADGrpNameAdmSuffix = -Admin
StrAzureADGrpNameBookSuffix = -Book
StrAzureADGrpNamePrefix = RES-
StrCalendarSuffix = Kalender
StrConfirmNewMail = byta mailadress för rummet
StrConfirmNewName = byta namn på rummet
StrConfirmNewOwner = byta ägare för rummet
StrConfirmPrefix = Du är på väg att
StrConfirmSuffix = Är du säker på att du vill fortsätta?
StrExchangeMembersNotSynched = Det finns användare som har bokningsbehörigheter för detta rum, som inte är listade i Azure. Dessa har fått behörigheten tilldelad manuellt. De anges genom 'False' i den tredje kolumnen.
StrExportFileName = Export rumsinfo
StrGettingAddress = Hämtar mailadress
StrGettingName = Hämtar namn
StrGettingOwner = Hämtar ägare
StrGettingRoomBookingInfoPublic = Hämtar inställning för synlighet för bokningsinformation
StrGettingRoomListMembership = Hämtar medlemskap i rumslistor
StrLogNewNameAddr = Nytt namn/adress
StrLogSync = Synkroniserad till Exchange
StrNameOrAddrNotUpd = Vid byte av namn eller adress behöver detta även reflekteras i det andra värdet. Detta verkar inte ha gjorts. Ska de nuvarande värdena i textrutorna användas för rummet?
StrNoAdAccountId = Inget AD-konto för angivet id
StrNoAdAccountOwner = Inget aktivt AD-konto för angiven ägare
StrNoAdmins = <Inga administratörer listade>
StrNoMailAccountOwner = Ingen mailbox aktiv för angiven ägare
StrNoMembersAzure = <Inga användare angivna i Azure>
StrNoMembersExchange = <Inga användare angivna i Exchange>
StrNoOwner = Ingen ägare angiven
StrNoUpdate = Rummet uppdaterades inte
StrNoUser = Ingen användare hittades som stämmer överens med
StrOpBookInfoNonPub = Bokningsinformation har ändrats till icke publik
StrOpBookInfoPub = Bokningsinformation har ändrats till publik
StrOpCopyOtherRoomDone = Kopiering av behörigheter från annat rum klar.
StrOpExportBegin = Startar export
StrOpExportEnd = Export utförd. Data skriven till fil
StrOpNameAddrChangeDone = Byte av namn och adress utförd
StrOpNewAdmin = tillagd som administratör i Azure
StrOpNewOwnerDone = Ägarebyte utförd
StrOpNewUser = tillagd med bokningsbehörighet
StrOpNoRoom = Inget rum hittades med namnet
StrOpRemoveAdmAz = togs bort från admingruppen i Azure
StrOpRemoveUserAz = togs bort från Azure-gruppen
StrOpSyncDone = Synkroniseringen är utförd
StrOwnerAttrPrefix = Owner:
StrUsersCopied = Lista över användare kopierade
'@
