ConvertFrom-StringData @'
AdmList = sysA, sysB, sysC
CompList = Comp1, Comp2
ComputerBaseInfo = Baseinformation
ComputerFolder = Computer
ComputerNoReinstall = Do NOT reinstall this PC
ComputerOffline = ... Failed
ComputerOfflineMessage = No connection with computer, or wrong computername. Try again.
ComputerOnline = Checking if computer is online
ComputerUnknownRole = Unknown-PC
ContentBtnAddScript = Add name of script to message
ContentBtnDisconnectComputer = Reset
ContentBtnGetComputerInfo = Get info
ContentBtnO365Connect = Connect
ContentBtnOutputList = List outputfiles
ContentBtnOutputListColumn = Filename
ContentBtnOutputOpenFile = Open file
ContentBtnRun = Run
ContentBtnSend = Send message
ContentFeedbackHeader = Report error / suggestions
ContentLblInTest = Only use this if you have been asked to
ContentLblMessageType = Type of message
ContentO365Start = Click 'Start' to open scriptmenu for Office 365-scripts
ContentOutputToolHeader = Outputfiler
ContentRBtnErrorReport = Report error
ContentRBtnSuggestion = Suggestion
InputComputerName = Computername
O365Folder = O365
OrgList = Org1|Org2|Org3
RoleList = Role1|Role2|Role3
ScriptContentInDev = Dev
ScriptContentInTest = Test
StrAdmPrefix = sys
StrBORole = AD_BORole
StrDGRTriggerName = Dont Install
StrInfoCopied = was copied to Clipboard
StrMailAddress = servicedesk@test.com
StrMailSender = From
StrNoOutputfiles = No outputfiles have been created
StrOFListing = Lists output files
StrOFOpenFile = Open file
StrOSParam = Operatingsystem
StrOtherOrg = Other organisation
StrScriptSuite = Scriptmenu
StrSMTP = smtp.test.com
StrSpecComp = Other computer
StrSplash = Läser in skript
'@
