ConvertFrom-StringData @'
AdmList = sysA, sysB, sysC
CompList = Comp1, Comp2
CompObjTitleBoot = Date of restart
CompObjTitleCompName = Computer name
CompObjTitleFreeSpace = Free disk space
CompObjTitleFreeSpaceLow = Free disk space (Low)
CompObjTitleIEVer = Internet Explorer version
CompObjTitleInst = Date of installation
CompObjTitleModel = Model
CompObjTitleNetAd = Network adapters
CompObjTitleOS = Operating system
CompObjTitleReinstAllowed = Reinstallation allowed
CompObjTitleReinstNotAllowed = Reinstallation not allowed
CompObjTitleRole = PC-role
CompObjTitleSinceBoot = Time since restart
CompObjTitleSN = Serial number
ComputerFolder = Computer
ComputerNoReinstall = DO NOT reinstall this PC
ComputerOffline = ... Failed
ComputerOfflineMessage = No contact with WinRM on computer, or incorrect computer name. Scripts dependent on WinRM will therefore not be able to start.
ComputerOnline = Checks that the computer is reachable
ComputerUnknownRole = Unknown-PC
ContentBtnAddScript = Add script name to message
ContentbtnComputerConnect = Get info
ContentbtnComputerDisconnect = Disconnect
ContentbtnFeedbackSend = Send message
ContentbtnListOutputFiles = List output files
ContentbtnO365Connect = Start
ContentbtnOpenOutputFile = Open file
ContentBtnRun = Run
ContentbtnSurveyCancel = Cancel
ContentbtnSurveySave = Save
ContentdgOutputFilesColDates = Last updated
ContentdgOutputFilesColNames = Filename
ContentlblComputerNameTitle = Enter computer name
ContentlblFeedbackType = Type of message
ContentLblInTest = Use only if asked
ContentlblRateTitle = Rate this version of
ContentlblSurvey = Feel free to leave a comment
ContentlblO65 = Click 'Start' to open the Office 365 Script Options Menu
ContentrbReport = Error report
ContentrbSuggestion = Suggestions
ContentrbSurveyRate1 = 1
ContentrbSurveyRate2 = 2
ContentrbSurveyRate3 = 3
ContentrbSurveyRate4 = 4
ContentrbSurveyRate5 = 5
ContenttiBaseInfo = Basic information
ContenttiOutputTool = Output files
ContenttiReportTool = Error report / Proposal
ContentWindow = Scriptmenu
ContentWindowSurvey = Please rate and comment on the script
LogConnectingToComp = Connects to
LogOpenO365 = Launches the O365 script menu
O365Folder = O365
OrgList = Org1|Org2|Org3
RoleList = Role1|Role2|Role3
ScriptContentInDev = Dev
ScriptContentInTest = Test
StrAdmPrefix = sys
StrBaseInfoDays = days
StrBaseInfoHours = hours
StrBaseInfoMinutes = minutes
StrBaseInfoNetAd = Network adapter
StrBORole = AD_BORole
StrInfoCopied = has been copied to the Clipboard
StrMailAddress = servicedesk@test.com
StrMailSender = From
StrNoOutputfiles = No output files created
StrOFListing = Lists output files
StrOFOpenFile = Open file
StrOtherOrg = Other organization
StrSMTP = smtp.test.com
StrSpecComp = Other computer
StrSplash = Reading scripts
'@
