ConvertFrom-StringData @'
ContentbtnCreateQuestion = Kopiera fråga om hjälp, till Katalog
ContentbtnOpenSummary = Öppna fil
ContentBtnReset = Reset
ContentBtnSearch = Search
ContentFilterTitle = Filer som matchar filter
ContentlblCaseNrTitle = Ange ärendenummer
ContentlblFileCountTitle = Totalt antal filer:
ContentLblFiles = Listar alla filer i mappar användaren har behörighet till.
ContentLblFiles2W = Listar alla filer uppdaterade de senaste två veckorna, i mappar användaren har behörighet till.
ContentLblFilterTitle = Vissa filer matchar filter
ContentlblIDTitle = Ange HSA-id för användare
ContentlblMDG = Filer med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentlblMDH = Filer i H-mappen med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentlblO = Mappar du inte har behörighet till, lägg ärende till katalog
ContentlblSummaryTitle = Sammanfattning skriven till:
ContentlblUserTitle = Användare:
ContentlblValuesTitle = Båda värden måste anges:
ContentlvColumnCreated = Skapad
ContentlvColumnName = Namn
ContentlvColumnUpdated = Uppdaterad
ContentrbAll = Sök alla filer
ContentrbAllToolTip = Hämtar alla filer, oberoende på datum. Vid sökning för alla filer, kommer detta att ske sekventiellt och tar då längre tid.
ContentrbLatest = Sök endast för senaste två veckorna
ContentrbLatestToolTip = Hämtar de filer som blivit ändrade inom de senaste två veckorna
ContentrbPrevDate = Sök från givet datum:
ContentrbPrevDateToolTip = Hämtar filer som ändrats efter angivet datum
ContenttiFilesHeader = Alla filer
ContenttiMDGHeader = Multipla filändelser på G:
ContenttiMDHHeader = Multipla filändelser på H:
ContenttiOHeader = Mappar du saknar behörighet till
ErrInvalidCaseNr = Ett giltigt ärendenummer måste anges.
ErrInvalidID = Inget konto hittades med angivet HSA-id.
MQCopied = Text har kopierats till clipboard
MQLCopied = Kopierat
StrOutput1 = Sökning av potentiella virus
StrOutput2 = Användare
StrOutput3 = Ärendenummer
StrOutput4 = Totalt antal filer:
StrOutputTimeline1 = Sökte: Filer uppdaterade senaste två veckorna
StrOutputTimeline2 = Sökte: Filer uppdaterade efter datum
StrOutputTimeline3 = Sökte: Alla tillgängliga filer
StrOutputTitle1 = Genomsökta mappar
StrOutputTitle2 = Alla funna filer
StrOutputTitle3 = Multipla filändelser
StrOutputTitle4 = Multipla filändelser
StrOutputTitle5 = Saknade behörighet för
WFilteringFolders = Filtrerar funna mappar
WGettingFiles = Startar hämtning av filer
WGettingFilesTitle = Hämtar filer i
WGettingFolders = Hämtar mappar
WLStart = Start
WQ1 = har anmält eventuellt virus i ärende
WQ2 = Mappar under H:\\ samt G:\\ har undersökts, men det saknas behörighet för mapparna nedan.
WQ3 = Kan ni hjälpa till att titta på dessa?
WWaitGettingFiles = Väntar hämtning av filer
'@
