ConvertFrom-StringData @'
ContentbtnAddAdmin = Add administrator
ContentbtnAddMember = Add user
ContentbtnAddRoomlist = Add to selected roomlist
ContentbtnBookingInfo = Save
ContentbtnCheck = Check
ContentbtnConfirmMessage = Save new message
ContentbtnConfirmMessageReset = Reset message
ContentbtnCopyAdmins = Copy administrators
ContentbtnCopyAll = Copy
ContentbtnCopyMembers = Copy users
ContentbtnCopyOtherRoom = Start process to copy
ContentbtnExport = Export
ContentbtnFetchAdmins = Get administrators
ContentbtnFetchMembers = Get users
ContentbtnFetchRLMembership = Get roomlistmembership
ContentbtnLocation = Save new office/location
ContentbtnRemoveMembersAzure = Remove user in Azure
ContentbtnRemoveMembersExchange = Remove user in Exchange
ContentbtnRemoveRoomlist = Remove from selected roomlist
ContentbtnRemoveSelectedAdmins = Remove
ContentbtnReset = Reset
ContentbtnRoomAddress = Change address
ContentbtnRoomName = Change name
ContentbtnRoomOwner = Change owner
ContentbtnRoomSearch = Search for room
ContentbtnSelectAll = Select all
ContentbtnSyncToExchange = Start synch
ContentdgAdmColMail = Mailaddress
ContentdgAdmColName = Name
ContentdgAzColMail = Mailaddress
ContentdgAzColName = Name
ContentdgAzColSync = Synched to Exchange
ContentdgExColMail = Mailaddress
ContentdgExColName = Name
ContentdgExColSync = Exists in Azure
ContentgAddAdmin = Add administrator
ContentgAddMembers = Add user
ContentgMembersAzure = Members according to Azure
ContentgMembersExchange = Members according to Exchange
ContentgRemoveSelectedAdmins = Remove administrator
ContentlblAddAdmin = Enter user
ContentlblAddMember = Enter user
ContentlblCheckRoomTitle = Enter roomname
ContentlblCopyAll = Copy users and administrators
ContentlblExport = Export information and users to an Excel-file
ContentlblLocation = Office/Location
ContentlblLogTitle = Log
ContentlblRemoveSelectedAdmins = Remove selected administrators
ContentlblRoomAddress = Address
ContentlblRoomName = Name
ContentlblRoomOwner = Owner
ContentlblRoomOwnerAddr = Address
ContentlblRoomOwnerID = Id
ContentlblRoomSearchTitle = Enter room to copy permissions from:
ContentlblSyncToExchange = Start synch to Exchange
ContentrbBookingInfoNotPublic = Not public
ContentrbBookingInfoPublic = Public
ContenttblBookingInfo = Should information about booked meetings in the rooms calendar, be publicly available?
ContenttblRoomListMembership = Membership in these roomlists
ContenttiAdmins = Administrators
ContenttiConfirmMessage = Confirmationmessage
ContenttiCopyOtherRoom = Copy from other room
ContenttiInfo = Info
ContenttiListMembership = Membership in roomlist
ContenttiMembers = Users
ContentttAddNewMembers = The export will only be of information that have been loaded. If, for example users haven't been loaded, they will not be exported to the Excel-file.
ErrAclTooBig = can not synchronize to Exchange. Too many members in Azure-group.
ErrAclTooBigQuit = can not synchronize to Exchange. Too many members in Azure-group. Synchronization is aborted.
ErrGen = Error when creating permission for the calendar:
ErrInvalidExternalUserId = does not exist. The person has probably quit.
ErrNotFound = No room was found
ExcelAdmMailTitle = Mailaddress
ExcelAdmTitle = Administrators
ExcelManUserMailTitle = Mailaddress
ExcelManUserTitle = Bookpermission, not synched
ExcelNoAdm = <No administrators>
ExcelNoAdmMail = -
ExcelNoConfirmMess = <No confirmationmessage>
ExcelNoRoomList = <Not member of a roomlist>
ExcelNoUser = <No users>
ExcelNoUserMail = -
ExcelRoomConfirmMess = Confirmationmessage for meetings
ExcelRoomLocTitle = Office/Location
ExcelRoomMailTitle = Mailaddress
ExcelRoomNameTitle = Roomname
ExcelRoomRoomListTitle = Roomlist
ExcelUserMailTitle = Mailaddress
ExcelUserTitle = Bookingpermission
LogAddRoomList = added to roomlist
LogAdmPerm = Administrator-permission
LogBookInfoNonPub = Book info not public
LogBookInfoPub = Book info public
LogBookingPerm = Booking-permission
LogCopyOtherRoom = Copied other permissions from other room
LogNewLoc = New location
LogNewResponceMessage = New confirmationmessage
LogRemRoomList = removed from roomlist
LogRemUsersAz = Remove user Az
LogRemUsersEx = Remove user Ex
StrAdminsCopied = List of administrators copied
StrAzureADGrpNameAdmSuffix = -Admin
StrAzureADGrpNameBookSuffix = -Book
StrAzureADGrpNamePrefix = RES-
StrCalendarSuffix = Calendar
StrConfirmNewMail = change maladdress for the room
StrConfirmNewName = change name for the room
StrConfirmNewOwner = change owner for the room
StrConfirmPrefix = You are about to
StrConfirmSuffix = Are you sure you want to continue?
StrExchangeMembersNotSynched = There are users that have permission to book this room, but are not listed in Azure. These have been added manualy in Exchange. This is marked with 'False' in the third column.
StrExportFileName = Export roominfo
StrGettingAddress = Getting mailaddress
StrGettingName = Getting name
StrGettingOwner = Gettng owner
StrGettingRoomBookingInfoPublic = Getting visibility setting for booking information
StrGettingRoomListMembership = Getting membership in roomlists
StrLogNewNameAddr = New name/mailaddress
StrLogSync = Synched to Exchange
StrNameOrAddrNotUpd = When changing name or address, this also needs to be reflected in the second value. This does not appear to have been done. Should the current values in the text boxes be used for the room?
StrNoAdAccountId = No AD-account for given Id
StrNoAdAccountOwner = No active AD-account for given owner
StrNoAdmins = <No administrators>
StrNoMailAccountOwner = No mailbox active to given owner
StrNoMembersAzure = <No users listed in Azure>
StrNoMembersExchange = <No users listed in Exchange>
StrNoOwner = No owner given
StrNoUpdate = The room was not updated
StrNoUser = No user was found with given id
StrOpBookInfoNonPub = Booking information was changed to not be public
StrOpBookInfoPub = Booking information has been changed to be public
StrOpCopyOtherRoomDone = Copying of permissions from other room, done.
StrOpExportBegin = Starts exporting
StrOpExportEnd = Export done. Data written to file
StrOpNameAddrChangeDone = Change of name and mailaddress, done
StrOpNewAdmin = added as administrator in Azure
StrOpNewOwnerDone = Change of ownership performed
StrOpNewUser = added with booking permission
StrOpNoRoom = No room was found the given name
StrOpRemoveAdmAz = was removed from the admin-group in Azure
StrOpRemoveUserAz = was remove the the user-group in Azure
StrOpSyncDone = Synchronization performed
StrOwnerAttrPrefix = Owner:
StrUsersCopied = List of users copied
'@
