ConvertFrom-StringData @'
CodeComputerMatch = (org1|org2|org3)(d|l)s\\d{7}
CodeComputerMismatch = ^(org4|org5)
CodeRoleMatch = (Role1|Role2|Role3)
ContentBtnReset = Reset
ContentDeselectAll = Avmarkera alla
ContentGetProfiles = Hämta profiler
ContentgwcID = Id
ContentgwcLastUse = Senast uppdaterad
ContentgwcName = Namn
ContentlblComputerName = Datornamn
ContentLogoutUsers = Logga ut alla användare
ContentRemoveSelected = Ta bort markerade profiler
ContentSelectAll = Markera alla
StrAdError = Annat fel vid kontroll mot AD
StrBackupFileName = Profilbackup
StrCheckOnline = Kontrollerar anslutning mot
StrConnect = Anslut till dator
StrDone = Klar
StrMessageLogout = Du kommer bli utloggad av Servicedesk om 10 sekunder
StrInfoLogout = Skickar meddelande om utloggning
StrLoggedOutUsers = användare utloggade
StrNameNotInAd = Datornamnet kan inte hittas i AD
StrNoProfiles = Inga profiler hittades
StrOffline = Är INTE tillgänglig
StrOnline = Är tillgänglig
StrOutputSummary = Rensat profiler på dator
StrProfiles = profiler
StrProfLoc = Sökväg för profil
StrRemoves = Tar bort Windows-profil och filer
StrStart = Påbörjar rensning av profiler
StrStartBackup = Startar backup för
StrTest = Testversion, profiler kommer inte tas bort och backup kommer inte skapas
StrUsersLoginSessions = användare har inloggningssessioner
StrUsersLoginSessionsLogOut = Logga ut dessa innan du fortsätter.
StrWrongName = Datornamnet är inte giltigt och kan inte kontrolleras mot AD
StrWrongOrg = Rensning av profiler utförs enbart på datorer tillhörandes Org1, Org2 och Org3. Denna tillhör annan organisation och deras separata IT-Service får hjälpa till.
StrWrongRole = Datorn har inte rätt PC-roll. En eller flera av dess roller kräver speciell hantering av IT-Service. Datorn har tilldelats följande roller:
'@
