ConvertFrom-StringData @'
CodeComputerMatch = (org1|org2|org3)(d|l)s\\d{7}
CodeComputerMismatch = ^(org4|org5)
CodeRoleMatch = (Role1|Role2|Role3)
ContentBtnReset = Reset
ContentDeselectAll = Deselect all
ContentGetProfiles = Get profiles
ContentgwcID = Id
ContentgwcLastUse = Last used
ContentgwcName = Name
ContentlblComputerName = Computername
ContentLogoutUsers = Log out all users
ContentRemoveSelected = Delete selected profiles
ContentSelectAll = Select all
StrAdError = Other error at verification towards AD
StrBackupFileName = Profilebackup
StrCheckOnline = Checking connection for
StrConnect = Connect to computer
StrDone = Done
StrMessageLogout = You will be logged out by Servicedesk in 10 seconds
StrInfoLogout = Sending message about logging out
StrLoggedOutUsers = user logged out
StrNameNotInAd = Computername can not be found in AD
StrNoProfiles = No profiles found
StrOffline = Is NOT available
StrOnline = Is available
StrOutputSummary = Deleted profiles on computer
StrProfiles = profiles
StrProfLoc = Pathway for profile
StrRemoves = Delete Windows-profile and files
StrStart = Starts deletion of profiles
StrStartBackup = Starts backup for
StrTest = Testversion, profiles will not be removed and no backups will be created
StrUsersLoginSessions = users have loginsessions
StrUsersLoginSessionsLogOut = Logout these before you continue.
StrWrongName = Not a valid computername and can not be verified in AD
StrWrongOrg = Deletion of profiles is only performed for computers within Org1, Org2 and Org3. This computer belongs to another organisation, so their IT-Service will have to do help.
StrWrongRole = Computer does not have the correct PC-Role. One or more of the roles demands that IT-Service do the deletion. The computer have the following roles:
'@
