ConvertFrom-StringData @'
CodeMsExchIgnoreOrg = OU=Org5
ContentbtnGetDelegates = Get delegations
ContentbtnGetDevices = Get devices
ContentbtnGetDists = Get distributiongroups the user is set owner for
ContentbtnGetIcon = Check if the user have a personalized icon
ContentbtnGetLogins = Get logins
ContentbtnGetShared = Get shared mailboxes the user is set owner for
ContentbtnID = Check O365-account status
ContentbtnRemoveIcon = Remove icon
ContentlblADActiveCheck = AD Active
ContentlblADCheck = AD
ContentlblADLockCheck = AD unlocked
ContentlblADMailCheck = Mailattribute
ContentlblADmsECheck = msExchMailboxGuid empty
ContentlblID = Enter id
ContentlblOAccountCheck = O365-account
ContentlblOExchCheck = Synced to Exchange
ContentlblOLicCheck = E3-license
ContentlblOLoginCheck = O365 login active
ContentlblOMigCheck = Member of O365-MigPilots
ContenttiDelegates = Delegations
ContenttiDevices = Registered devices
ContenttiDists = Distributiongroups
ContenttiIcon = Usericon
ContenttiLogins = Registered logins
ContenttiShared = Shared mailboxes
ErrNoCalendar = Could not find calendar
StrCalendar = Calendar
StrDgDelegatesTitleFolder = Folder
StrDgDelegatesTitlePerm = Permissions
StrDgDelegatesTitleUser = User
StrDgDistsTitleName = Distributiongroup
StrDgDistsTitleSmtp = SMTP address
StrDgSharedTitleName = Shared mailbox
StrDgSharedTitleSmtp = SMTP address
StrErrAD = Could not connect to AD-server. Import ActiveDirectory module.
StrErrAdDisabled = AD-account not active (Disabled)
StrErrAdLocked = AD-account is locked
StrErrADNF = ID could not be found in AD
StrErrMsExch = msExchMailboxGuid is not empty in AD
StrErrNoMail = Mailattribute not synced to AD
StrIgnoreMsExch = Works in Org5, ignoring msExchMailboxGuid
StrInbox = Inbox
StrLastLogin = Last successful AzureAD-login:
StrLastTeamsLogin = Last successful Teams-login:
StrNoDists = <Not owner for any distributiongroup>
StrNoImage = No personalized icon set
StrNoLogin = No logins registered
StrNoShared = <Not owner for any shared mailbox>
StrO365IgnoreLicense = Works in Org5, is not assign a license.
StrO365LoginDisabled = Login to O365-account not active
StrO365NoAzAdConnection = Not connected to AzureAD
StrO365NoExchConnection = Not connected to Exchange
StrO365NoLicens = No E3-license
StrO365NoMig = Not member of O365-MigPilots
StrO365NoO365 = No O365-account created. Aborting the rest of the tests
StrO365NotFound = No O365-account created
StrO365NotFoundExchange = Mailbox not created in Exchange
StrToday = Today
StrYesterday = Yesterday
'@
