ConvertFrom-StringData @'
ContentbtnCheckForUpdates = Search for updates
ContentbtnClearErrorLogSearch = Cancel search
ContentbtnClearLogSearch = Cancel search
ContentbtnDiffCancel = Abort
ContentbtnDiffOpenBoth = Open both
ContentbtnDiffOpenDev = Open the Dev file
ContentbtnDiffOpenProd = Open the Prod file
ContentbtnDoRollback = Roll back file version
ContentbtnErrorLogSearch = Search
ContentbtnListRollbacks = List rollbacks
ContentbtnListSurveys = List surveys
ContentbtnLogSearch = Search
ContentbtnOpenErrorLog = Open error log
ContentbtnOpenOutputFile = Open file
ContentbtnOpenRollbackFile = Open file
ContentbtnReadErrorLogs = Load error logs
ContentbtnReadLogs = Load logs
ContentbtnUpdatedInProdOpenBothFiles = Open both files
ContentbtnUpdatedInProdOpenDevFile = Open the Dev file
ContentbtnUpdatedInProdOpenDiffs = Open diff window
ContentbtnUpdatedInProdOpenProdFile = Open the Prod file
ContentbtnUpdateFailedScripts = Update checked files
ContentbtnUpdateScripts = Update selected files
ContentbtnUpdatesOpenBothFiles = Open both files
ContentbtnUpdatesOpenDevFile = Open the Dev file
ContentbtnUpdatesOpenDiff = Open diff window
ContentbtnUpdatesOpenProdFile = Open the Prod file
ContentcbLogsFilterSuccessFailed = Failed
ContentcbLogsFilterSuccessSuccess = Successful
ContentcbRollbackFilterTypePs1 = ps1
ContentcbRollbackFilterTypePs1Tooltip = Script file
ContentcbRollbackFilterTypePsd1 = psd1
ContentcbRollbackFilterTypePsd1Tooltip = Data/Localization-file
ContentcbRollbackFilterTypePsm1 = psm1
ContentcbRollbackFilterTypePsm1Tooltip = Module-file
ContentcbRollbackFilterTypeTxt = txt
ContentcbRollbackFilterTypeTxtTooltip = Documentation / Information file
ContentcbRollbackFilterTypeXaml = xaml
ContentcbRollbackFilterTypeXamlTooltip = GUI definition file
ContentcbShowDevFiles = View files in dev
ContentdgDiffListColDevRow = Row in dev file
ContentdgDiffListColLineNr = Line number
ContentdgDiffListColProdRow = Row in prod file
ContentdgErrorLogsColLogDate = Logging time
ContentdgFailedUpdatesColAcceptedVerb = Approved verb
ContentdgFailedUpdatesColInvalidLocalizations = Invalid localizations
ContentdgFailedUpdatesColName = Script
ContentdgFailedUpdatesColObsoleteFunctions = Obsolete functions
ContentdgFailedUpdatesColOrphandLocalizations = Orphand localizations
ContentdgFailedUpdatesColScriptInfo = Script information
ContentdgFailedUpdatesColTODOs = Forgotten TODO notes
ContentdgFailedUpdatesColUpdateAnyway = Update anyway
ContentdgFailedUpdatesColWritesToLog = Writes log
ContentdgInvalidLocalizationsColLineNumber = Line number
ContentdgInvalidLocalizationsColScriptLine = Text line
ContentdgInvalidLocalizationsColScriptVar = Variable
ContentdgLogsColLogDate = Logging time
ContentdgLogsColOperator = Operator
ContentdgLogsColSuccess = Success
ContentdgObsoleteFunctionsColFunctionName = Function name
ContentdgObsoleteFunctionsColHelpMessage = Information
ContentdgObsoleteFunctionsColLineNumbers = Line number
ContentdgOrphandLocalizationsColValue = Variable value
ContentdgOrphandLocalizationsColVariable = Variable name
ContentdgRollbacksColFileName = Filename
ContentdgRollbacksColType = Filetype
ContentdgRollbacksColUpdated = Updated
ContentdgRollbacksColUpdatedBy = Updated by
ContentdgSIColHeaderInfoDesc = Description
ContentdgSIColHeaderTitle = Missing information
ContentdgSurveyAnswersColComment = Comment
ContentdgSurveyAnswersColDate = Date
ContentdgSurveyAnswersColOperator = User
ContentdgSurveyAnswersColRating = Grade
ContentdgSurveyNoComment = <No comment specified>
ContentdgSurveyScriptsColScriptName = Scriptname
ContentdgSurveyScriptsColSurveyCount = Survey count
ContentdgTDColHeaderTextL = Text line
ContentdgTDColHeaderTextLN = Line number
ContentdgUpdatesColDevUpd = Updated in development
ContentdgUpdatesColName = Name
ContentdgUpdatesColPath = Path
ContentdgUpdatesColProdState = Development phase
ContentdgUpdatesColProdUpd = Updated in production
ContentgbErrorInfo = Information about the error message
ContentlblErrLogComputerName = Computer name
ContentlblErrorMessage = Error message
ContentlblLogComputerNameTitle = Computer name
ContentlblLogErrorLogTitle = Errorlog
ContentlblLogOutputFileTitle = File for output
ContentlblLogTextTitle = Logtext
ContentlblLogUserInputTitle = Specified input
ContentlblOperator = Operator
ContentlblRollbackFiltersTitle = Filter options
ContentlblRollbackFilterTypeTitle = Filetype
ContentlblRollbackFilterUpdatedByTitle = Updated by
ContentlblSeverity = Error category
ContentlblSurveyFilterTitle = Filter visible ratings
ContentlblSurveyScriptVersionTitle = Script version (date of last update)
ContentlblSurveyTotSumTitle = Number of survey responses
ContentlblUserInput = Specified input
ContentNoAcceptedVerb = No accepted verb is used in the script name. This is used for grouping different scripts and their purposes in the scriptmenu to make it easier to find the right script
ContenttbDevTitle = files in development
ContenttblInfo = Only update the files you know you have modified yourself
ContenttblUpdatedInProd = These have been updated in production, but not in dev.
ContenttbProdTitle = files in production
ContenttbTestTitle = files in test phase
ContenttiErrorLogs = Errorlogs
ContenttiFailedUpdates = Failed updates
ContenttiLogs = Logs
ContenttiRollback = Rollbackmachine
ContenttiSurveys = Surveys for script in testphase
ContenttiUpdated = Updated
ContenttiUpdatedInProd = Updated in prod
ContenttiUpdates = Updates
ContentWindow = Script Administration
LogFailedUpdates = script failed to update
LogFailedUpdatesName = Script name
LogFailedUpdatesTestResults = Test result:
LogOpenDiffWindow = Checks file diff
LogUpdatedIntro = Updated
StrCheckingFilesInProd = Checks files in production
StrCheckingUpdates = Checking for updates
StrDiffRowAdded = < Row added>
StrDiffRowRemoved = < Row removed>
StrErrorlogsNotLoaded = Error logs have not been loaded
StrFailedTestCount = Number of tests that failed
StrLogSearchNoType = No type selected
StrNewDataFile = New PS data file
StrNewFileTitle = < New file >
StrNewGuiFile = New GUI-file
StrNewLocFile = New localization-file
StrNewOtherFile = New file
StrNewScript = New script
StrNoFailedSelected = No files selected for update
StrNoUpdaterSpecified = <Not specified>
StrNoUpdates = No updated files
StrOtherScriptState = Other
StrRollbackDone = File rolled back
StrRollbackName = updated
StrRollbackPathNotFound = The file is not found in production. This file has probably been replaced by another file, or renamed. The file should therefore not be rolled back.
StrRollbackVerification = Do you want to replace the file in production with this file?
StrRollbackVerificationDate = File version to roll back:
StrRollbackVerificationPath = File to replace:
StrScriptInfoDescAuthor = Who created the script. He is also responsible for its functionality and updating
StrScriptInfoDescDescription = A clear description of what the script does
StrScriptInfoDescState = What phase of development does the script have; Dev, Test or Prod. Must be specified to insure if it is ready to be updated, needs to be tested or is ready for production
StrScriptInfoDescSynopsis = A line of text with a short description of the script. This appears next to the button to start the script.
StrScriptState = Associated scripts in
StrSplListSurveys = Retrieves surveys
StrSplReadErrorLogs = Reads error logs
StrSplReadLogs = Reads log files
StrUpdates = updated files
StrUpdatesInProd = files have been modified in production, but not in dev
'@
