ConvertFrom-StringData @'
ContentbtnCheckForUpdates = Search for updates
ContentbtnDoRollback = Roll back file version
ContentbtnListRollbacks = List rollbacks
ContentbtnOpenErrorLog = Open errorlog
ContentbtnOpenOutputFile = Open file
ContentbtnOpenRollbackFile = Open file
ContentbtnReadErrorLogs = Load error logs
ContentbtnReadLogs = Load logs
ContentbtnUpdateScripts = Update selected files
ContentdgErrorLogsColLogDate = Logging time
ContentdgLogsColLogDate = Logging time
ContentdgLogsColOperator = Administrator
ContentdgLogsColSuccess = Success
ContentdgRollbacksColDate = File date
ContentdgRollbacksColUpdatedBy = Updated by
ContentdgUpdatesColDevUpd = Updated in development
ContentdgUpdatesColName = Name
ContentdgUpdatesColPath = Path
ContentdgUpdatesColProdState = Development phase
ContentdgUpdatesColProdUpd = Updated in production
ContentgbErrorInfo = Information about the error message
ContentlblErrorMessage = Error message
ContentlblLogErrorLogTitle = Errorlog
ContentlblLogOutputFileTitle = File for output
ContentlblLogTextTitle = Log text
ContentlblLogUserInputTitle = Specified input
ContentlblOperator = Administrator
ContentlblSeverity = Error category
ContentlblUserInput = Specified input
ContenttblInfo = Only update the files you know you have modified yourself
ContenttblUpdatedInProd = These have been updated in production, but not in dev.
ContenttiErrorLogs = Error logs
ContenttiLogs = Logs
ContenttiRollback = Rollback machine
ContenttiUpdated = Updated
ContenttiUpdatedInProd = Updated in prod
ContenttiUpdates = Updates
ContentWindow = Script Administration
StrErrorlogsNotLoaded = Error logs have not been loaded
StrLogIntro = Updated
StrNewDataFile = New PS data file
StrNewGuiFile = New GUI file
StrNewLocFile = New localization file
StrNewOtherFile = New file
StrNewScript = New script
StrNoUpdates = No updated files
StrRollbackDone = File rolled back
StrRollbackName = updated
StrRollbackPahNotFound = The file is not found in production. This file has probably been replaced by another file, or renamed. The file should therefore not be rolled back.
StrRollbackVerification = Do you want to replace the file in production with this file?
StrRollbackVerificationDate = File version to roll back:
StrRollbackVerificationPath = File to replace:
StrScanSummary = in phase
StrScriptState = Associated script in
StrSplReadErrorLogs = Reading error logs
StrSplReadLogs = Reading log files
StrSummaryUp = files updated
StrUpdates = updated files
StrUpdatesInProd = files have been modified in production, but not in dev
'@
