ConvertFrom-StringData @'
ContentbtnAddNewMembers = Lägg till
ContentbtnCheck = Kontrollera distributionslista
ContentbtnCopyMembers = Kopiera medlemslista
ContentbtnCopyOutput = Kopiera lösningsmeddelande
ContentbtnDistAddress = Ändra adress
ContentbtnDistName = Ändra namn
ContentbtnDistOpenForExternal = Ändra
ContentbtnDistOwner = Byt ägare
ContentbtnImport = Importera från clipboard
ContentbtnRemoveMembers = Ta bort markerade medlemmar
ContentbtnReset = Avbryt
ContentbtnStartReplace = Starta ersättningen
ContentdgMembersMailTitle = E-mailadress
ContentdgMembersNameTitle = Namn
ContentdgSuggestionsColDispName = Visningsnamn
ContentlblAddNewMembers = Lägg till medlem/-ar
ContentlblDist = Ange distributionslista
ContentlblDistAddress = Mailadress
ContentlblDistName = Visningsnamn
ContentlblDistOwner = Ägare
ContentlblSuggestionsTitle = Flera distributionslistor hittades som stämmer överens med sökningen
ContentrbDistOpenForExternalNo = Tillåt inte
ContentrbDistOpenForExternalYes = Tillåt
ContenttbDistOpenForExternal = Kan användas av externa användare?
ContenttiInfo = Info
ContenttiMembers = Medlemmar
ContenttiReplaceAll = Ersätt alla medlemmar
ContentttAddNewMembers = Endast mailadresser, separera med semikolon ( ; )
ErrLogNewOwner = Byte av ägare till:
ErrLogRemove = Ta bort medlemmar
ErrNotFoundInAd = Hittas inte i AD
LogAddNewMembers = Lägg till användare
LogMembersCopied = Kopierade medlemmar
LogNewNameAddress = Nytt namn/adress
LogNewNameAddressAzGrps = Azure-grupper:
LogNewOwner = Satte ny ägare:
LogOutputCopied = Kopierade output
LogRemove = Ta bort medlemmar
LogReplaceAll = Ersätta alla medlemmar
LogReplaceAllUIDist = Distributionslista:
LogReplaceAllUIMemb = Medlemmar
LogSetForExternalUse = Ändrat utnyttjande från externa användare till:
StrAzureGroupPrefix = DL-
StrCheckingAddress = Verifierar mailadresser
StrCopiedMembers = Lista över medlemmar har kopierats till Clipboard
StrCopiedOutput = Sammanfattning av medlemsersättningar har kopierats till Clipboard
StrFound = hittades och har lagts in i distributionslistan
StrImported = adresser inlästa
StrMembersCopiedTitle = Medlemmar av
StrNameOrAddrNotUpd = Vid byte av namn eller adress behöver detta även reflekteras i det andra värdet. Detta verkar inte ha gjorts. Ska de nuvarande värdena i textrutorna användas för distributionslistan?
StrNotFound = domän-adresser hittades inte, de ignorerades
StrNotMail = Dessa värden är inte korrekta mailadresser och ignorerades
StrNoUpdate = Distributionslistan uppdaterades inte
StrOrgDomain = @test.com
StrOtherOrg = adresser utanför regionen hittades inte som kontaktobjekt i Exchange (nya har skapats)
StrRemovingMembers = Tar bort nuvarande medlemmar
StrSummary = har nu fått alla medlemmar ersatta enligt listan bifogad i ärendet. Nedan följer sammanfattning av ändringen:
# Possible titles for a listcolumn, like if addresses are copied from Excel
StrTitleMatch = "mail", "email","emails","e-mail","e-mails","epost","e-post","epostadresser","e-postadresser","epostadress","e-postadress","emailadress"
'@
