ConvertFrom-StringData @'
CodeGetGGroupRead1 = "$( $Customer )_$( $entry )_file_UserR"
CodeGetGGroupRead2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetGGroupWrite1 = "$( $Customer )_$( $entry )_file_UserC"
CodeGetGGroupWrite2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetRGroupRead1 = "$( $Customer )_$( $entry )_file_UserR"
CodeGetRGroupRead2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetRGroupRead3 = "$( $FolderName )$( $Customer )_$( $entry )_file_02_UserR"
CodeGetRGroupRead4 = "$( $FolderName )$( $Customer )_$( $entry )_file_03_UserR"
CodeGetRGroupWrite1 = "$( $Customer )_$( $entry )_file_UserC"
CodeGetRGroupWrite2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserC"
CodeGetRGroupWrite3 = "$( $FolderName )$( $Customer )_$( $entry )_file_02_UserC"
CodeGetRGroupWrite4 = "$( $Customer )_$( $entry )_file_03_UserC"
CodeGetSGroupRead1 = "$( $Customer )_$( $entry )_file_UserR"
CodeGetSGroupRead2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserR"
CodeGetSGroupWrite1 = "$( $Customer )_$( $entry )_file_UserC"
CodeGetSGroupWrite2 = "$( $FolderName )$( $Customer )_$( $entry )_file_01_UserC"
ContentbtnPerform = Perform changes
ContentbtnUndo = Abort
ContentFoldersChosen = Chosen folders
ContentlblDisk = Choose disk
ContentlblFolderList = Choose folder with doubleclick
ContentlblFolderSearch = Search (whole or part of name)
ContentlblLog = Performed changes
ContentlblUsersForReadPermission = Read-permission
ContentlblUsersForRemovePermission = Remove permission
ContentlblUsersForWritePermission = Read-/write-permission
StrConfirm1 = Do you for
StrConfirm2 = folders, perform
StrConfirm3 = changes
StrConfirmDups = Some value/-s are listed for more than one type of permission. Correct this and run again.
StrConfirmDupsTitle = Duplicates
StrConfirmErr = Some values do not have AD-objects.
StrConfirmTitle = Continue?
StrEGroupDn = EGroupDn
StrEGroupIdName = EGroupIdName
StrEGroupOrg = EGroupOrgID
StrFinIntro = These folders have had permission-changes acording to list below
StrFinished1 = changes performed
StrFinished2 = A message with performed changes have been copied to the clipboard
StrFinNoAccounts = Found no account for
StrFinNoAdGroups = Found no permissiongroup for these groups
StrFinPermRead = Created read-permission for
StrFinPermRem = Remove permissions for
StrFinPermWrite = Created read-/write-permission for
StrGetFolders = Fetching folders...
StrNoPerm = You do not have the correct permissions to run this script.
StrNoPermTitle = Missing permissions
StrOpErrLogFile = \\Errorlogs\\
StrOpGroup = Role_Operations_Group
StrOpLogPath = \\\\domain.test.com\\Results\\FolderTool
StrPermRead = Read-permission
StrPermReadWrite = Read-/write-permission
StrPermRemove = Remove permission
StrPreping = Preparing...
StrSDGroup = Role_Servicedesk_Group
StrSign = With kind regards
StrSignOp = IT
StrSignSD = IT, Servicedesk
StrStart = Setting grouppermissions
StrStartPrep = Getting users for
StrTitle = Add/remove folderpermissions
StrTitleProgressGroups = Getting AD-groups
'@
