ConvertFrom-StringData @'
ContentbtnPerform = Perform
ContentbtnUndo = Cancel
ContentlblApp = Select application
ContentlblAppGroupList = Select the app group by double-clicking
ContentlblGroupsChosen = Selected app groups
ContentlblLog = Changes made
ContentlblUsersAddPermission = Create permissions
ContentlblUsersRemovePermission = Remove permissions
ContentWindowTitle = Remove / add app permissions
ErrMessageGetAppGroups = Retrieving appgroups
ErrMessageGetUser = Retrieving users
ErrMessageSetPassword = Set password
ErrMessageSetSettings = Set settings
ErrScriptPermissions = You do not have the necessary permissions to run this script
LogInputAdd = For addition: 
LogInputRemove = For removal:
LogMessageAdd = Was given permission:
LogMessageRemove = Permission removed:
LogNew = New authorization
LogNoAccount = Could not find account for the following
LogRemove = Remove permissions
MsgMessageIntro = Has made the following changes to the following
MsgNew = New authorization
MsgNewPassword = New password
MsgNoAccount = Could not find account for the following
MsgRemove = Remove permissions
QCont1 = Do you want to
QCont2 = perform
QCont3 = changes
QContErr = Some users do not have AD accounts
QContTitle = Continue
StrBORoleGrp = Role_Servicedesk_BO
StrDuplicates = There are duplicates of values in the lists. Correct these and run again
StrDuplicatesTitle = Duplicates
StrFinishMessage = changes made. A solution message has been copied to the clipboard
StrFinishMessageTitle = Done
StrGetADGroups = Loading app groups ...
StrGettingUser = Retrieving users
StrLogMessage = Application
StrOpGrp = Role_Operations
StrOpLogPath = \\\\domain.test.com\\Results\\FolderTool
StrPreparing = Preparing ...
StrProgressTitle = Applies group permissions
StrSigGen = Sincerely
StrSigSD = IT, Servicedesk
StrSpecOrg = org7
'@
