ConvertFrom-StringData @'
ContentBtnPerform = Perform
ContentBtnRefetchGroups = Hämta
ContentBtnRefetchGroupsTT = Läs in grupperna igen
ContentBtnUndo = Cancel
ContentTblApp = Select application
ContentTblAppGroupList = Select the app group by double-clicking
ContentTblGroupsChosen = Selected app groups
ContentTblLog = Changes made
ContentTblUsersAddPermission = Create permissions
ContentTblUsersRemovePermission = Remove permissions
ContentWindowTitle = Remove / add app permissions
ErrMessageGetAppGroups = Retrieving appgroups
ErrMessageGetUser = Retrieving users
ErrMessageSetPassword = Set password
ErrMessageSetSettings = Set settings
ErrScriptPermissions = You do not have the necessary permissions to run this script
LogInputAdd = For addition: 
LogInputRemove = For removal:
LogMessageAdd = Was given permission:
LogMessageRemove = Permission removed:
MsgMessageIntro = Has made the following changes to the following
MsgNew = New authorization
MsgNewPassword = New password
MsgNoAccount = Could not find account for the following
MsgRemove = Remove permissions
QCont1 = Do you want to
QCont2 = perform
QCont3 = changes
QContErr = Some users do not have AD accounts
QContTitle = Continue
StrAddedUsersTitle = Added permission
StrBORoleGrp = Role_Servicedesk_BO
StrDuplicates = There are duplicates of values in the lists. Correct these and run again
StrDuplicatesTitle = Duplicates
StrErrorUsersTitle = ID missing in AD
StrFinishMessage = changes made. A solution message has been copied to the clipboard
StrFinishMessageTitle = Done
StrGetADGroups = Loading app groups ...
StrGettingUser = Retrieving users
StrGroupsTitle = Grupper
StrLogMessage = Application
StrLogOut = For the authorization to take effect, the account needs to be logged out and then logged in again.
StrOpGrp = Role_Operations
StrOpLogPath = \\\\domain.test.com\\Results\\FolderTool
StrPreparing = Preparing ...
StrProgressTitle = Applies group permissions
StrRemovedUsersTitle = Permission removed
StrSigGen = Sincerely
StrSigSD = IT, Servicedesk
StrSpecOrg = org7
'@
