ConvertFrom-StringData @'
CodeIdMatch = doms
CodeLockedLogsLocation = \\\\loc.test.se\\LockedoutLogs$
CodeOuSpecDep = OU=SpecDep,DC=Org,DC=se
CodeShareAccMatch = f(org3)|(org2)|(org1)
ContentbtnActivate = Activate account
ContentbtnCancel = Cancel
ContentBtnListLocked = List lockouts
ContentbtnUnlock = Unlock account
ContentDgLockedListHeader0 = Time
ContentDgLockedListHeader1 = Computer
ContentDgLockedListHeader2 = Domaincontroler
ContentlblID = Enter ID or account name
ContentLblLockedList = Lockout was made at these computers
ContentWindow = AD account control
ErrLogActivate = Activation of account
ErrLogExtendPassword = Extension of password validity. Errormessage
ErrLogUnlock = Unlocking account. Error message
ErrMsgActivate = Could not activate account. Error message
ErrMsgActivatePermission = You do not have permission to activate this account, see routine for more info
ErrMsgActivatePermissionSpecDep = The user belongs to SpecDep, refer to Lab that activates (See routine)
ErrMsgExtendPassword = Could not extend validate period for password. Errormessage
ErrMsgExtendPasswordPermission = You do not have permission to extend password validity for this account, see routine for more info on who can unlock it
ErrMsgExtendPasswordPermissionSpecDep = The user belongs to SpecDep, refer to SpecIT who can extend the validity period of the password (See routine)
ErrMsgUnlock = Could not unlock account. Error message
ErrMsgUnlockPermission = You do not have permission to unlock this account, see routine for more info on who can unlock it
ErrMsgUnlockPermissionSpecDep = The user belongs to SpecDep, refer to Lab that unlocks the account (See routine)
LogActivated = Activated
LogBlockedUser = inactive > Op
LogDisabledUser = inactive
LogErrActivate = Error - Activate
LogErrExtendPassword = Error - Extension of password validity
LogErrUnlock = Error - Unlocking account
LogExpiredPassword = password validity passed
LogFutureExpiry = active password
LogLocked = locked
LogLockedLookUp = List lockouts
LogManualExpiry = manual validity period > Op
LogManualExpiryEnded = manual validity period passed > Op
LogNeverEndingPassword = neverending password
LogPasswordChange = password change at the next login
LogPasswordExtended = Password validity extended
LogUnlocked = Unlocked
StrActivated = Account activated.
StrActive = Active
StrDoNotActivate = THIS USER SHOULD NOT BE ACTIVATED, CONTACT OP FOR MORE INFO
StrExpiredPassword = Password Status: Password is over 200 days old and has expired. Extend the validity of the existing password using the 'Extend Password' button below. Password expired
StrFutureExpiry = Password Status: Password Expires
StrLocked = The account is locked due to for many incorrect login attempts, see the heading 'Account is locked' in routine
StrManualExpiry = Validity period: The account has a manual validity date (Account expires). The account is managed by Op. The validity period expires
StrManualExpiryEnded = Validity period: The account has a manual expiration date that has passed (the Account expires date has passed). Escalate the case to Op. The account expired
StrNeverEndingPassword = Password status: Password never expires
StrNotFoundInAd = not found in AD
StrPasswordChange = Password status: A password change is queued ('User must change password at next logon' is pre-checked). Ask the user to log in with the new password they should have recently received. Alternatively, set a new password for the user (Follow the routine for changing passwords in AD according to the user's organization affiliation).
StrPasswordExtended = The validity period of the password has been extended.
StrReadUser = Loaded user
StrSharedAccWorkstation = The sharedaccount is connected to:
StrUnlocked = The account has been unlocked.
StrUserActive = Account Status: The account is enabled and unlocked
StrUserBlocked = Account status: The account is deactivated and SHOULD NOT BE ACTIVATED! Escalate the case to Op
StrUserDisabled = Account status: The account is disabled (disabled): To activate the account, see the heading 'Account has been Disabled / Disabled' in article: AD - Locked account
'@
