ConvertFrom-StringData @'
ContentbtnAbort = Abort
ContentbtnCreateQuestion = Copy question for help, to Operations
ContentbtnOpenFolder = Open folder
ContentbtnOpenFolderTT = Open the folder the file is located in
ContentbtnOpenSummary = Open file
ContentbtnPrep = Prepare search
ContentbtnReset = Reset
ContentbtnRunVirusScan = Run virus scan
ContentbtnSearchExt = Search for file extension
ContentbtnSearchExtTT = Search for file extension on Google
ContentbtnSearchFileName = Search for file names
ContentbtnSearchFileNameTT = Search for the file name on Google
ContentbtnStartSearch = Start search
ContentcbExpandGroups = Expand all file type groups
ContentcbSetAccountDisabled = Disable the account
ContentgbDatePicker = Date of oldest file change
ContentgbInfo = Summary
ContentgbSearch = Search settings
ContentgbSettings = Settings
ContentlblCaseNrTitle = Enter case number
ContentlblFileCountTitle = Total number of files:
ContentLblFiles = Lists all files in folders the user has access to.
ContentLblFiles2W = Lists all files updated in the last two weeks, in folders the user has access to.
ContentlblFilterMatch = Files that match the specified filter
ContentlblFolderCountTitle = Number of folders searched:
ContentlblFolderListTitle = Waiting for file list from the following folders
ContentlblIDTitle = Enter user-id
ContentlblMDG = Files with multiple points in the file name (potentially multiple file extensions)
ContentlblMDH = Files in the H folder with multiple points in the file name (potentially multiple file extensions)
ContentlblO = Folders you do not have access to, add case to operations
ContentlblSummaryTitle = Summary written to:
ContentlblUserTitle = User:
ContentlblValuesTitle = Both values must be specified:
ContentlvColumnCreated = Created
ContentlvColumnName = Name
ContentlvColumnUpdated = Updated
ContentrbAll = Search all files
ContentrbAllToolTip = Retrieves all files, with changes made in the last 60 days. When searching for all files, it may take significantly longer.
ContentrbLatest = Last two weeks
ContentrbLatestToolTip = Retrieves the files that have been modified within the last two weeks
ContentrbPrevDateToolTip = Retrieves files that have changed after the specified date
ContenttbPrevDateText = From the specified date
ContenttiFilesHeader = All files
ContenttiFilterMatchHeader = Matches filters
ContenttiMDGHeader = Multiple file extensions on G:
ContenttiMDHHeader = Multiple file extensions on H:
ContenttiOHeader = Folders you do not have permission to
ErrInvalidCaseNr = A valid case number must be entered.
ErrInvalidID = No account was found with the specified user-id.
ErrLogInvalidId = No user account was found with the specified id
LogScannedFile = Started virus scan
LogScannedFileTitle = Filename
StrDescSplit = on
StrEnableUser = Should the user account be activated?
StrErrUserNotFound = no user have that id
StrFileSearchFinished = Finished searching for files
StrLogMsgCaseNr = Case number
StrLogMsgFileSearchAborted = Aborted filesearch
StrLogMsgFilesMatchingFilterCount = Number of files that match the specified filter:
StrLogMsgFilsWithDoubleExtG = Number of files with possible double file extensions on G:
StrLogMsgFilsWithDoubleExtH = Number of files with possible double file extensions on H:
StrLogMsgFolderSearch = Searching for folders
StrLogMsgId = User ID
StrLogMsgOpenFolder = Opened folder
StrLogMsgOtherPermCount = Number of folders where permission was missing:
StrLogMsgSearchExt = Searched for file extension
StrLogMsgSearchFileName = Searched for filename
StrLogMsgSearchTime = Search time
StrLogMsgTotNumFiles = Total number of files
StrLogQuestionCopied = Copied
StrLogScriptStart = Start
StrMultiFileVirusSearch = Multiple files have been selected, which will take longer, the more files selected
StrNoExtension = <No file extension>
StrNoFilesFound = < No files found >
StrOPFilteringFolders = Filters found folders
StrOPGettingFiles = Starts retrieving files
StrOPGettingFolders = Retrieving folders
StrOPWaitGettingFiles = Awaiting retrieval of file
StrOutput1 = Search for potential viruses
StrOutput2 = User
StrOutput3 = Case number
StrOutput4 = Total number of files:
StrOutputTimeline1 = Searched: Files updated in the last two weeks
StrOutputTimeline2 = Searched: Files updated by date
StrOutputTimeline3 = Searched: All available files
StrOutputTitleAllFiles = All found files
StrOutputTitleFilterMatch = These files matched filters
StrOutputTitleFilterMatch2 = Specified filter:
StrOutputTitleFolders = Searched folders
StrOutputTitleFoldersOtherPerm = Missing permissions for the following folders
StrOutputTitleMultiDotG = Multiple file extensions G:
StrOutputTitleMultiDotH = Multiple file extensions H:
StrQuestion1 = has reported a possible virus in the case
StrQuestion2 = Folders under H:\\ and G:\\ have been examined, but there is no permission for the folders below.
StrQuestion3 = Can you help look at these?
StrQuestionCopied = Text has been copied to the clipboard
StrUserAccountAlreadyLocked = Account is already locked
StrWaitingFileSearch = <Waiting for file search to start>
StrVerbVirusScan = Search for threats
'@
