ConvertFrom-StringData @'
ContentBtnAbort = Abort
ContentBtnCloseStreamsList = Close
ContentBtnCreateQuestion = Copy question to Operations
ContentBtnOpenFolder = Open folder
ContentBtnOpenFolderTT = Open the folder the file is located in
ContentBtnOpenSummary = Open file
ContentBtnPrep = Prepare search
ContentBtnReset = Reset
ContentBtnRunVirusScan = Run virusscan
ContentBtnSearchExt = Search for file extension
ContentBtnSearchExtTT = Search for file extension on Google
ContentBtnSearchFileName = Search for file name
ContentBtnSearchFileNameTT = Search for the file name on Google
ContentBtnShowFileStreams = Show filestreams
ContentBtnStartSearch = Start search
ContentCbSetAccountDisabled = Disable the account
ContentDgtcStreamsDataSize = Size
ContentDgtcStreamsName = Name of filestream
ContentLvColumnCreated = Created
ContentLvColumnName = Name
ContentLvColumnOwner = Owner
ContentLvColumnSize = Size
ContentLvColumnStreams = File streams
ContentLvColumnUpdated = Updated
ContentRbAllToolTip = Retrieves all files, with changes made in the last 60 days. When searching for all files, it may take significantly longer.
ContentRbLatestToolTip = Retrieves the files that have been modified within the last two weeks
ContentRbPrevDateToolTip = Retrieves files that have changed after the specified date
ContentStreamsListInfo = Alternate streams for file
ContentTblCaseNrTitle = Enter case number
ContentTblCbExpandGroups = Expand all file type groups
ContentTblCbGroupExtensions = Group files by file type
ContentTblFileCountTitle = Total number of files:
ContentTblFilterMatch = Files that match the specified filter
ContentTblFolderCountTitle = Number of folders searched:
ContentTblFolderListTitle = Waiting for file list from the following folders
ContentTblGroupInputTitle = Settings
ContentTblGroupSearchSettingsTitle = Searchsettings
ContentTblGroupSummaryTitle = Summary
ContentTblIdTitle = Enter id of user
ContentTblMDG = Files with multiple points in the file name (potentially multiple file extensions)
ContentTblMDH = Files in the H folder with multiple points in the file name (potentially multiple file extensions)
ContentTblO = Folders you do not have access to, escalate case to Operations
ContentTblPrevDateText = From the specified date
ContentTblRbAllText = Search all files
ContentTblRbLatest = Last two weeks
ContentTblSummaryTitle = Summary written to:
ContentTblUserTitle = User:
ContentTblValuesTitle = Both values must be specified
ContentTiFilesHeader = All files
ContentTiFilterMatchHeader = Matches filters
ContentTiMDGHeader = Multiple file extensions on G:
ContentTiMDHHeader = Multiple file extensions on H:
ContentTiOHeader = Folders you do not have permission to
LogScannedFile = Ran virus scan
LogScannedFileTitle = Filename
MsgRecycleBin = The file is in the Trash and cannot be checked.
StrDescSplit = on
StrEnableUser = Should the user account be activated?
StrErrUserNotFound = No user with that id
StrFileOwner = User
StrFileSearchFinished = Finished searching for files
StrLogMsgCaseNr = Casenumber
StrLogMsgFileSearchAborted = Abort filesearch
StrLogMsgFilesMatchingFilterCount = Number of files that match the specified filter:
StrLogMsgFilesScannedForVirus = These files have been checked with antivirus
StrLogMsgFilesWithDoubleExtG = Number of files with possible double file extensions on G:
StrLogMsgFilesWithDoubleExtH = Number of files with possible double file extensions on H:
StrLogMsgFolderSearch = Searching for folders
StrLogMsgId = User-id
StrLogMsgOpenFolder = Opened folder
StrLogMsgOtherPermCount = Number of folders where permissions were missing:
StrLogMsgSearchExt = Searched for file extension
StrLogMsgSearchFileName = Searched for filename
StrLogMsgSearchTime = Search time
StrLogMsgTotNumFiles = Total number of files
StrLogQuestionCopied = Copied
StrLogScriptStart = Start
StrMultiFileVirusSearch = Most files have been selected, which will take longer, the more files selected
StrNoExtension = <No file extension>
StrNoFilesFound = < No files found >
StrOPFilteringFolders = Filters found folders
StrOPGettingFiles = Starts downloading files
StrOPGettingFolders = Retrieving folders
StrOPWaitGettingFiles = Awaiting file download
StrOutput1 = Search for potential viruses
StrOutput2 = User
StrOutput3 = Casenumber
StrOutput4 = Total number of files:
StrOutputTimeline1 = Searched: Files updated in the last two weeks
StrOutputTimeline2 = Searched: Files updated by date
StrOutputTimeline3 = Searched: All available files
StrOutputTitleAllFiles = All found files
StrOutputTitleFilterMatch = These files matched filters
StrOutputTitleFilterMatch2 = Specified filter:
StrOutputTitleFolders = Searched folders
StrOutputTitleFoldersOtherPerm = Missing permissions for the following folders
StrOutputTitleMultiDotG = Multiple file extensions G:
StrOutputTitleMultiDotH = Multiple file extensions H:
StrQuestion1 = has reported any virus in the case
StrQuestion2 = Folders under H:\\ and G:\\ have been examined, but there is no permission for the folders below.
StrQuestion3 = Can you help look at these?
StrQuestionCopied = Text has been copied to the clipboard
StrUserAccountAlreadyLocked = Account already disabled
StrWaitingFileSearch = <Waiting for file search to start>
StrVerbVirusScan = Search for threats
'@
