ConvertFrom-StringData @'
CodeRegExDomain = @test.com$
ContentbtnAddAdmin = Lägg till
ContentbtnAddMember = Lägg till
ContentbtnCheck = Hämta
ContentbtnCopyUsers = Kopiera
ContentbtnFetchAdmins = Läs in administratörer
ContentbtnFetchMembers = Läs in användare
ContentbtnRemoveMembersAzure = Ta bort medlem i Azure
ContentbtnRemoveMembersExchange = Ta bort medlem i Exchange
ContentbtnRemoveSelectedAdmins = Ta bort
ContentbtnReset = Återställ
ContentbtnSMAddress = Byt adress
ContentbtnSMName = Byt namn
ContentbtnSMOwner = Byt ägare
ContentbtnSyncToExchange = Starta synk
ContentcbAddMemberLoc = Azure, Exchange, Båda
ContentcbAddMemberPerm = Läsbehörighet, Full behörighet
ContentdgAdminsMailTitle = Mailadress
ContentdgAdminsNameTitle = Namn
ContentdgMembersMailTitle = Mailadress
ContentdgMembersNameTitle = Namn
ContentdgMembersPermissionTitle = Behörighetstyp
ContentdgSuggestionsColDispName = Visningsnamn
ContentdgSuggestionsColPrimSmtp = Mailadress
ContentexpAddAdmin = Lägg till administratör
ContentexpAddMembers = Lägg till medlem
ContentgAddAdmin = Ny administratör
ContentgMembersAzure = Medlemmar enligt Azure
ContentgMembersExchange = Medlemmar enligt Exchange
ContentgRemoveSelectedAdmins = Ta bort administörer
ContentlblAddAdmin = Ange id eller mailadress för användaren
ContentlblAddMember = Ange id eller mailadress
ContentlblAddMemberLoc = Lägg till i:
ContentlblAddMemberPerm = Behörighetstyp:
ContentlblCopyUsers = Kopiera medlemmar och admins
ContentlblRemoveSelectedAdmins = Ta bort markerade administratörer
ContentlblSM = Ange namn eller mailadress för funktionsbrevlåda
ContentlblSMAddress = Primär SMTP-adress
ContentlblSMName = Namn
ContentlblSMOwner = Ägare
ContentlblSMOwnerAddr = Mailadress
ContentlblSMOwnerId = Id
ContentlblSuggestionsTitle = Flera funktionsbrevlådor hittades som matchar söktermen. Välj en genom att dubbelklicka
ContentlblSyncToExchange = Starta manuell synkronisering till Exchange
ContentOwnerAddrTT = Detta fält är låst och kan inte ändras. Ange istället id för den som ska anges som ägare
ContenttiAdmins = Administratörer
ContenttiInfo = Info
ContenttiMembers = Medlemmar
ErrLogNewAdm = Ny admin
ErrLogNewMem = Ny medlem
ErrLogNewNameAddrGetGrps = Sätta nytt namn/adress (Hämta grupper)
ErrLogNewNameAddrSetAzGrps = Sätta nytt namn/adress (Sätta Azure-grupper)
ErrLogNewNameAddrSetMailbox = Sätta nytt namn/adress (Sätt mailbox)
ErrLogNewOwner = Sätta nya ägare
ErrLogRemoveAdm = Ta bort admin
ErrLogRemoveMemAzGrp = Ta bort behörighet Azure
ErrLogRemoveMemGSOBT = Ta bort behörighet att skicka som ombud
ErrLogRemoveMemPermExc = Ta bort behörighet Exchange
ErrLogSearchMailbox = Sökning av mailbox
ErrLogSyncFull = Synkroniserar fullständigabehörigheter
ErrLogSyncRead = Synkroniserar läsbehörigheter
ErrMsgAdAccNotActive = AD-konto är inte aktivt, personen har ev slutat
ErrMsgNoAdAccount = AD-konto finns inte
ErrMsgNoMailAccount = Hittar inget aktivt mailkonto med denna adress
ErrMsgNoOwner = Ingen ägare angiven
ErrMsgOwnerAdDisabled = Användare är inte aktiv i AD
ErrMsgOwnerAdError = Fel uppstod vid sökning i AD
ErrMsgOwnerAdNotFound = Hittar ingen användare med angivet ID
LogNewAdm = Ny admin
LogNewMember = Ny medlem
LogNewMemberUILoc = Tjänst:
LogNewMemberUIPerm = Behörighet:
LogNewMemberUIUser = Användare:
LogNewNameAddr = Nytt namn/adress
LogNewNameAddrUIAddr = Mailadress:
LogNewNameAddrUIName = Namn:
LogNewOwner = Ny ägare
LogRemoveAdm = Ta bort admin
LogRemoveMemAz = Ta bort behörighet Azure
LogRemoveMemExc = Ta bort behörighet Exchange
LogSearchMailbox = Sökning av mailbox
LogSync = Startat synkronisering
StrAzureADGrpNameAdmSuffix = -Admins
StrAzureADGrpNameFullSuffix = -Full
StrAzureADGrpNamePrefix = MB-
StrAzureADGrpNameReadSuffix = -Read
StrConfirmNewOwner = byta ägare på funktionsbrevlådan
StrConfirmPrefix = Du är på väg att
StrConfirmRemoveMembers = användare är på väg att tas bort i
StrConfirmRename = byta namn på funktionsbrevlådan
StrConfirmSuffix = Är du säker på att du vill fortsätta?
StrGettingAdmins = Hämtar administratörer
StrGettingMailbox = Hämtar funktionsbrevlåda
StrGettingMembers = Hämtar medlemmar
StrNameOrAddrNotUpd = Vid byte av namn eller adress behöver detta även reflekteras i det andra värdet. Detta verkar inte ha gjorts. Ska de nuvarande värdena i textrutorna användas för funktionsbrevlådan?
StrNoAdmins = <Inga administratörer angivna i Azure>
StrNoUpdate = Funktionsbrevlådan uppdaterades inte
StrOwnerAttrPrefix = Owner:
StrPermFull = Full behörighet
StrPermRead = Läsbehörighet
StrPermSend = Behörighet att skicka som ombud
StrPermSendOnBehalf = Kan skicka som ombud
StrUsersCopied = Användare har kopierats till Clipboard
'@
