ConvertFrom-StringData @'
ContentbtnAddRoom = Lägg till rum
ContentbtnAddRoomCancel = Avbryt
ContentbtnAddRoomOk = OK
ContentbtnChangeOwner = Byt ägare
ContentbtnCreateRoomList = Skapa ny rumslista
ContentbtnCreateRoomListCancel = Avbryt
ContentbtnCreateRoomListOk = OK
ContentbtnRemoveRoom = Ta bort markerat rum
ContentdgRoomListsColListName = Namn på rumslista
ContentdgRoomsInListColRoomName = Rumsnamn
ContentlblAddRoomTitle = Ange namn på rum
ContentlblCreateRoomListTitle = Ange namn och maildress på den nya rumslistan
ContentlblListRoomsTitle = Rum kopplade till rumslistan
ContentlblOwnerChangeInfo = Ange id, mailadress eller namn i Exchange för ny ägare
ContentlblOwnerTitle = Ägare:
ContentlblRoomListsList = Befintliga rumslistor
ErrLogAddRoom = Lägga till rum
ErrLogNewList = Ny rumslista
ErrLogNewOwner = Ny ägare
ErrLogRemRoom = Ta bort rum
ErrMsgNoRoom = Inget rum hittades med angivet namn
ErrMsgNoRoomsInList = <Inga rum är kopplade till rumslistan>
ErrMsgNoUsr = Hittade ingen användare som stämmer överens med angiven text
ErrMsgSame = Personen är redan angiven som ägare
LogAddRoom = Lagd till rum
LogAddRoomUIRL = Rumslista:
LogAddRoomUIRoom = Rum:
LogNewList = Ny rumslista
LogNewListUIRLName = Namn
LogNewOwner = Ny ägare
LogRemoveRoom = Ta bort rum
LogRemoveRoomUIRL = Rumslista:
LogRemoveRoomUIRoom = Rum:
StrGettingLists = Hämtar rumslistor
StrGettingsRoomsInList = Hämtar rum kopplade till rumslistan
'@
