ConvertFrom-StringData @'
CodeMsExchIgnoreOrg = OU=Org5
ContentbtnGetDelegates = Hämta delegeringar
ContentbtnGetDevices = Hämta enheter
ContentbtnGetDistsMember = Hämta medlemskap
ContentbtnGetDistsOwner = Hämta ägarskap
ContentbtnGetIcon = Kontrollera om användaren har individuell ikon
ContentbtnGetLogins = Hämta inloggningar
ContentbtnGetSharedMember = Hämta medlemskap
ContentbtnGetSharedOwner = Hämta ägarskap
ContentbtnID = Kontrollera O365 status
ContentbtnRemoveIcon = Ta bort ikon
ContentlblADActiveCheck = AD Aktiv
ContentlblADCheck = AD
ContentlblADLockCheck = AD Olåst
ContentlblADMailCheck = Mailattribut
ContentlblADmsECheck = msExchMailboxGuid tom
ContentlblID = Ange användar-id
ContentlblLastO365Login = Senast lyckade Office 365-inloggning:
ContentlblLastTeamsLogin = Senast lyckade Teams-inloggning:
ContentlblOAccountCheck = O365-konto
ContentlblOExchCheck = Synkat till Exchange
ContentlblOLicCheck = E3-licens
ContentlblOLoginCheck = O365 inloggning aktiv
ContentlblOMigCheck = Medlem i O365-MigPilots
ContenttiDelegates = Delegeringar
ContenttiDevices = Registrerade enheter
ContenttiDists = Distributionslistor
ContenttiDistsMember = Medlemskap
ContenttiDistsOwner = Ägarskap
ContenttiIcon = Användarikon
ContenttiLogins = Registrerade inloggningar
ContenttiShared = Funktionsbrevlådor
ContenttiSharedMember = Medlemskap
ContenttiSharedOwner = Ägarskap
ErrNoCalendar = Kunde inte hitta kalendern
StrCalendar = Kalender
StrDgDelegatesTitleFolder = Mapp
StrDgDelegatesTitlePerm = Behörigheter
StrDgDelegatesTitleUser = Användare
StrDgDistsMemberTitleName = Distributionslista
StrDgDistsMemberTitleSmtp = SMTP adress
StrDgDistsOwnerTitleName = Distributionslista
StrDgDistsOwnerTitleSmtp = SMTP adress
StrDgSharedMemberTitleName = Funktionsbrevlåda
StrDgSharedMemberTitlePermission = SMTP adress
StrDgSharedOwnerTitleName = Funktionsbrevlåda
StrDgSharedOwnerTitleSmtp = SMTP adress
StrDoneGettingLogings = Logindates received
StrErrAD = Kan inte ansluta till AD-server. Läs in ActiveDirectory modulen.
StrErrAdDisabled = AD-konto ej aktivt (Disabled)
StrErrAdLocked = AD-konto är låst
StrErrADNF = ID hittas inte i AD
StrErrMsExch = msExchMailboxGuid är inte tomt i AD
StrErrNoMail = Mailattributet ej synkroniserat till AD
StrGettingLoggins = Hämtar inloggningar, detta kan ta någon minut
StrGettingLogginsDelegates = (kan ej göras samtidigt som inloggningar hämtas)
StrIgnoreMsExch = Anställd inom Org5, ignorerar msExchMailboxGuid
StrInbox = Inkorg
StrNoDistsMember = <Inte medlem i någon distributionslista>
StrNoDistsOwner = <Inte ägare för någon distributionslista>
StrNoImage = Ingen bild angiven på kontot
StrNoLogin = Inga inloggningar registrerade
StrNoMailDelegates = <Inga delegeringar för mail>
StrNoSharedMember = <Inte medlem i någon funktionsbrevlåda>
StrNoSharedOwner = <Inte ägare för någon funktionsbrevlåda>
StrO365IgnoreLicense = Anställd inom Org5, tilldelas ingen licens.
StrO365LoginDisabled = Inloggning med O365-konto inaktiverat
StrO365NoAzAdConnection = Inte ansluten till AzureAD
StrO365NoExchConnection = Inte ansluten till Exchange
StrO365NoLicens = E3-licens saknas
StrO365NoMig = Är inte medlem i O365-MigPilots
StrO365NoO365 = O365-konto har inte skapats. Avbryter resten av testerna.
StrO365NotFound = O365-konto har inte skapats
StrO365NotFoundExchange = Mailbox inte skapad i Exchange
StrToday = Idag
StrYesterday = Igår
'@
