ConvertFrom-StringData @'
CodeMsExchIgnoreOrg = OU=Org5
ContentbtnGetDelegates = Hämta delegeringar
ContentbtnGetDevices = Hämta enheter
ContentbtnGetDists = Hämta distributionslistor användaren är ägare för
ContentbtnGetIcon = Kontrollera om användaren har individuell ikon
ContentbtnGetLogins = Hämta inloggningar
ContentbtnGetShared = Hämta funktionsbrevlådor användaren är ägare för
ContentbtnID = Kontrollera O365 status
ContentbtnRemoveIcon = Ta bort ikon
ContentlblADActiveCheck = AD Aktiv
ContentlblADCheck = AD
ContentlblADLockCheck = AD Olåst
ContentlblADMailCheck = Mailattribut
ContentlblADmsECheck = msExchMailboxGuid tom
ContentlblID = Ange id
ContentlblOAccountCheck = O365-konto
ContentlblOExchCheck = Synkat till Exchange
ContentlblOLicCheck = E3-licens
ContentlblOLoginCheck = O365 inloggning aktiv
ContentlblOMigCheck = Medlem i O365-MigPilots
ContenttiDelegates = Delegeringar
ContenttiDevices = Registrerade enheter
ContenttiDists = Distributionslistor
ContenttiIcon = Användarikon
ContenttiLogins = Registrerade inloggningar
ContenttiShared = Funktionsbrevlådor
ErrNoCalendar = Kunde inte hitta kalendern
StrCalendar = Kalender
StrDgDelegatesTitleFolder = Mapp
StrDgDelegatesTitlePerm = Behörigheter
StrDgDelegatesTitleUser = Användare
StrDgDistsTitleName = Distributionslista
StrDgDistsTitleSmtp = SMTP adress
StrDgSharedTitleName = Funktionsbrevlåda
StrDgSharedTitleSmtp = SMTP adress
StrErrAD = Kan inte ansluta till AD-server. Läs in ActiveDirectory modulen.
StrErrAdDisabled = AD-konto ej aktivt (Disabled)
StrErrAdLocked = AD-konto är låst
StrErrADNF = ID hittas inte i AD
StrErrMsExch = msExchMailboxGuid är inte tomt i AD
StrErrNoMail = Mailattributet ej synkroniserat till AD
StrIgnoreMsExch = Anställd inom Org5, ignorerar msExchMailboxGuid
StrInbox = Inkorg
StrLastLogin = Senast lyckade AzureAD-inloggning:
StrLastTeamsLogin = Senast lyckade Teams-inloggning:
StrNoDists = <Inte ägare för någon distributionslista>
StrNoImage = Ingen bild angiven på kontot
StrNoLogin = Inga inloggningar registrerade
StrNoShared = <Inte ägare för någon funktionsbrevlåda>
StrO365IgnoreLicense = Anställd inom Org5, tilldelas ingen licens.
StrO365LoginDisabled = Inloggning med O365-konto inaktiverat
StrO365NoAzAdConnection = Inte ansluten till AzureAD
StrO365NoExchConnection = Inte ansluten till Exchange
StrO365NoLicens = E3-licens saknas
StrO365NoMig = Är inte medlem i O365-MigPilots
StrO365NoMsolConnection = Inte ansluten till MsolService
StrO365NoO365 = O365-konto har inte skapats. Avbryter resten av testerna.
StrO365NotFound = O365-konto har inte skapats
StrO365NotFoundExchange = Mailbox inte skapad i Exchange
StrToday = Idag
StrYesterday = Igår
'@
