ConvertFrom-StringData @'
ContentbtnAddAdmin = Add administrator
ContentbtnAddMember = Add user
ContentbtnAddRoomlist = Add to selected roomlist
ContentbtnBookingInfo = Save
ContentbtnCheck = Check
ContentbtnConfirmMessage = Save new message
ContentbtnConfirmMessageReset = Reset message
ContentbtnCopyAdmins = Copy administrators
ContentbtnCopyAll = Copy
ContentbtnCopyMembers = Copy users
ContentbtnCopyOtherRoom = Start process to copy
ContentbtnExport = Export
ContentbtnFetchAdmins = Get administrators
ContentbtnFetchMembers = Get users
ContentbtnFetchRLMembership = Get roomlistmembership
ContentbtnLocation = Save new office/location
ContentbtnRemoveMembersAzure = Remove user in Azure
ContentbtnRemoveMembersExchange = Remove user in Exchange
ContentbtnRemoveRoomlist = Remove from selected roomlist
ContentbtnRemoveSelectedAdmins = Remove
ContentbtnReset = Reset
ContentbtnRoomName = Change name
ContentbtnRoomOwner = Change owner
ContentbtnRoomSearch = Search for room
ContentbtnSelectAll = Select all
ContentbtnSyncToExchange = Start synch
ContentdgAdminsColMail = Emailaddress
ContentdgAdminsColName = Name
ContentdgMembersAzureColMail = Emailaddress
ContentdgMembersAzureColName = Name
ContentdgMembersAzureColSync = Synced to Exchange
ContentdgMembersExchangeColMail = Emailaddress
ContentdgMembersExchangeColName = Name
ContentdgMembersExchangeColSync = Listed in Azure
ContentdgMembersOtherRoomColMail = Emailaddress
ContentdgMembersOtherRoomColName = Name
ContentdgSuggestionsColMail = Emailaddress
ContentdgSuggestionsColName = Name
ContentexpAddMember = Add member
ContentexpAddRemAdm = Add/remove administrator/-s
ContentgAddAdmin = Add administrator
ContentgAddMember = Add user
ContentgMembersAzure = Members according to Azure
ContentgMembersExchange = Members according to Exchange
ContentgRemoveSelectedAdmins = Remove administrator
ContentlblAddAdmin = Enter user
ContentlblAddMember = Enter user
ContentlblCheckRoomTitle = Enter roomname
ContentlblCopyAll = Copy users and administrators
ContentlblExport = Export information and users to an Excel-file
ContentlblLocation = Office/Location
ContentlblLogTitle = Log
ContentlblRemoveSelectedAdmins = Remove selected administrators
ContentlblRoomAddress = Address
ContentlblRoomName = Name
ContentlblRoomOwner = Owner
ContentlblRoomOwnerAddr = Address
ContentlblRoomOwnerID = Id
ContentlblRoomSearchTitle = Enter room to copy permissions from:
ContentlblSuggestionsTitle = Several rooms match the search term, select the desired room by double-clicking
ContentlblSyncToExchange = Start synch to Exchange
ContentrbBookingInfoNotPublic = Not public
ContentrbBookingInfoPublic = Public
ContenttblBookingInfo = Should information about booked meetings in the rooms calendar, be publicly available?
ContenttbMemberInfo = There are users who have booking privileges for this room, which are not listed in Azure. These have probably been granted the authorization manually in Exchange. They are indicated by 'False' in the third column.
ContenttiAdmins = Administrators
ContenttiConfirmMessage = Confirmationmessage
ContenttiCopyOtherRoom = Copy from other room
ContenttiInfo = Info
ContenttiListMembership = Membership in roomlist
ContenttiMembers = Users
ContentttAddNewMembers = The export will only be of information that have been loaded. If, for example users haven't been loaded, they will not be exported to the Excel-file.
ErrAclTooBig = can not synchronize to Exchange. Too many members in Azure-group.
ErrAclTooBigQuit = can not synchronize to Exchange. Too many members in Azure-group. Synchronization is aborted.
ErrGen = Error when creating permission for the calendar:
ErrInvalidExternalUserId = does not exist. The person has probably quit.
ErrLogAccessRights = Set policy for access rights
ErrLogAccessRightsUIPolicy = Policy:
ErrLogAccessRightsUIRoom = Room:
ErrLogAddAdminAdd = Add admin
ErrLogAddAdminSet = Set group
ErrLogAddAdminUIGrp = Group
ErrLogAddAdminUIUsr = User
ErrLogAddMemCalProc = Add member
ErrLogAddToRoomlist = Add to room list
ErrLogAddToRoomlistUIRoom = Room:
ErrLogAddToRoomlistUIRoomlist = Room list:
ErrLogCopyOtherRoom = Copy permissions from another room
ErrLogCopyPermUIOtherRoom = Copy from
ErrLogCopyPermUIUsers = User:
ErrLogNewLoc = Change location
ErrLogNewNameAddr = New name / address
ErrLogNewNameAddrUIGrp = AzureAD-group
ErrLogNewOwner = New owner
ErrLogRemAdmGrp = Remove admin
ErrLogRemoveUserAzure = Remove member in Azure
ErrLogRemRoomList = Removed from room list
ErrLogRemRoomListUIRoomList = Room list:
ErrLogRemUsrAzUIRoom = Group:
ErrLogRemUsrExcRemMbPerm = Delete user in Exchange
ErrLogRemUsrExcSetCalProc = Delete user in Exchange
ErrLogSetConfirmMsg = Update confirmation message
ErrLogSync = Synchronization of permissions
ErrMsgNewOwnerNotActive = Not active in AD
ErrMsgNewOwnerNotAddr = Email address is missing in AD
ErrMsgNewOwnerNotInAd = Not found in AD
ErrMsgNoAdAccountOwner = No active AD account for specified owner
ErrMsgNoMailAccountOwner = No mailbox active for specified owner
ErrNotFound = No room was found
ErrRoomNotFound = Room was not found
ExcelAdmMailTitle = Emailaddress
ExcelAdmTitle = Administrators
ExcelManUserMailTitle = Emailaddress
ExcelManUserTitle = Bookpermission, not synched
ExcelNoAdm = <No administrators>
ExcelNoAdmMail = -
ExcelNoConfirmMess = <No confirmationmessage>
ExcelNoRoomList = <Not member of a roomlist>
ExcelNoUser = <No users>
ExcelNoUserMail = -
ExcelRoomConfirmMess = Confirmationmessage for meetings
ExcelRoomLocTitle = Office/Location
ExcelRoomMailTitle = Emailaddress
ExcelRoomNameTitle = Roomname
ExcelRoomRoomListTitle = Room list
ExcelUserMailTitle = Emailaddress
ExcelUserTitle = Bookingpermission
LogAccessRights = Set policy for access rights
LogAddAdmin = Add admin
LogAddMemUIRoom = Room:
LogAddMemUIUser = User:
LogAddRoomList = added to roomlist
LogAddRoomListUIRoom = Room:
LogAdmPerm = Administrator-permission
LogBookInfoNonPub = Book info not public
LogBookInfoPub = Book info public
LogBookingPerm = Booking-permission
LogCopyAdmin = Copied admins
LogCopyMembers = Copied members
LogCopyOtherRoom = Copied other permissions from other room
LogCopyOtherRoomUIFrom = From room:
LogCopyOtherRoomUIUsers = User:
LogExported = Exported data
LogMsgOpRemoveAdmAz = was removed from the admin group in Azure
LogNewLoc = New location
LogNewLocUILoc = Specified location
LogNewLocUIRoom = Room:
LogNewOwner = New owner
LogNewResponseMessage = New confirmationmessage
LogRemAdmGrp = Remove administrators
LogRemRoomListUIRoomList = Room list:
LogRemUsersAz = Remove user Az
LogRemUsersEx = Remove user Ex
LogRoomSearch = Search
LogSync = Synchronized to Exchange
StrAdminsCopied = List of administrators copied
StrAzureADGrpNameAdmSuffix = -Admin
StrAzureADGrpNameBookSuffix = -Book
StrAzureADGrpNamePrefix = RES-
StrConfirmNewName = change name for the room
StrConfirmNewOwner = change owner for the room
StrConfirmPrefix = You are about to
StrConfirmSuffix = Are you sure you want to continue?
StrExportFileName = Export rumsinfo
StrGettingRoomListMembership = Retrieves membership in room lists
StrLogNewNameAddr = New name / address
StrNameOrAddrNotUpd = When changing name or address, this also needs to be reflected in the other value. This does not appear to have been done. Should the current values in the text boxes be used for the room?
StrNoAdmins = <No administrators>
StrNoMembersAzure = <No users listed in Azure>
StrNoMembersExchange = <No users listed in Exchange>
StrNoOwner = No owner given
StrNoUpdate = The room was not updated
StrNoUser = No user was found with given id
StrOpBookInfoNonPub = Booking information was changed to not be public
StrOpBookInfoPub = Booking information has been changed to be public
StrOpCopyOtherRoomDone = Copying of permissions from other room, done.
StrOpExportBegin = Starts exporting
StrOpExportEnd = Export done. Data written to file
StrOpNameAddrChangeDone = Change of name and mailaddress, done
StrOpNewAdmin = added as administrator in Azure
StrOpNewOwnerDone = Change of ownership performed
StrOpNewUser = added with booking permission
StrOpNoRoom = No room was found the given name
StrOpRemoveUserAz = was removed from the group in Azure
StrOpRemoveUserExc = was remove the group in Exchange
StrOpSyncDone = Synchronization performed
StrOpSynched = synchronized
StrOwnerAttrPrefix = Owner:
StrUsersCopied = List of users copied
'@
