ConvertFrom-StringData @'
CodeRegExDomain = @test.com$
ContentbtnAddAdmin = Add
ContentbtnAddMember = Add
ContentbtnCheck = Check
ContentbtnCopyUsers = Copy
ContentbtnFetchAdmins = Get administrators
ContentbtnFetchMembers = Get members
ContentbtnRemoveMembersAzure = Remove member in Azure
ContentbtnRemoveMembersExchange = Remove member in Exchange
ContentbtnRemoveSelectedAdmins = Remove
ContentbtnReset = Reset
ContentbtnSMAddress = Change address
ContentbtnSMName = Change name
ContentbtnSMOwner = Change owner
ContentbtnSyncToExchange = Start sync
ContentcbAddMemberLoc = Azure, Exchange, Both
ContentcbAddMemberPerm = Read permission, Full permission
ContentdgAdminsMailTitle = Emailaddress
ContentdgAdminsNameTitle = Name
ContentdgMembersMailTitle = Emailaddress
ContentdgMembersNameTitle = Name
ContentdgMembersPermissionTitle = Permissionrtype
ContentgAddAdmin = Add administrator
ContentgAddMembers = Add member
ContentgMembersAzure = Members in Azure
ContentgMembersExchange Member in Exchange
ContentgRemoveSelectedAdmins = Remove administrators
ContentlblAddAdmin = Enter new administrator
ContentlblAddMember = Enter userid or emailaddress
ContentlblAddMemberLoc = Add to:
ContentlblAddMemberPerm = Permissiontype:
ContentlblCopyUsers = Copy members and administrators
ContentlblRemoveSelectedAdmins = Remove selected administrators
ContentlblSM = Enter name or emailaddress for the shared mailbox
ContentlblSMAddress = Primary SMTP address
ContentlblSMName = Name
ContentlblSMOwner = Owner
ContentlblSMOwnerAddr = Emailaddress
ContentlblSMOwnerId = User id
ContentlblSyncToExchange = Start a sync of users to Exchange
ContenttiAdmins = Administrators
ContenttiInfo = Info
ContenttiMembers = Members
StrAzureADGrpNameAdmSuffix = -Admin
StrAzureADGrpNameFullSuffix = -Full
StrAzureADGrpNamePrefix = MB-
StrAzureADGrpNameReadSuffix = -Read
StrConfirmNewOwner = change owner of the shared mailbox
StrConfirmPrefix = You are about to
StrConfirmRemoveMembers = users are about to be removed in
StrConfirmRename = change name of shared mailbox
StrConfirmSuffix = Are you sure you want to continue?
StrImmutableIdPrefix = ID-
StrLogNewNameAddr = New name/address
StrLogNewOwner = New owner
StrNameOrAddrNotUpd = When changing name or emailaddress, this change needs to be reflected in the other value. This does not appears to have happened. Do you want to use the values in the textboxes as new values for the shared mailbox?
StrNoAdAccount = AD-account does not exist
StrNoAdmins = <No administrators specified in Azure>
StrNoMailAccount = No active mailaccount with this address
StrNoUpdate = The shared mailbox was not updated
StrOwnerAttrPrefix = Owner:
StrPermFull = Full permission
StrPermRead = Read permission
StrPermSend = Permission to send on behalf of
StrPermSendOnBehalf = Can send on behalf of
StrUsersCopied = Users have been copied to 
'@
